/*
    BASIC EBNF

    Syntax is compatible wtih Railroad Diagram Generator (https://www.bottlecaps.de/rr/ui).
*/

/* 
    Whitespace strategy: consume whitespace
        1. Before a statement keyword (parse_statement)
        2. Before literal text within statement (parse_statement)
        3. Before a (binary) operator (parse_operator)
        4. Before a unary operator (parse_unary_operator)
        5. Before a print operator (parse_print_separators)
        6. Before the opening parenthesis of a subexpression (parse_primary_expression)
        7. Before a closing parentheses in any context (parse_close)
        8. Before an argument separator (parse_argument_separator)
        9. Before a channel number (TBD)
       10. Before the semicolon that separates prompt text from variables in INPUT (TBD)
       11. Before a string (parse_string) or number (parse_number)
       12. Before a variable name (parse_variable) or function name (parse_function)
*/

program_line ::= number statement (_ ':' statement)*

statement ::= _ (
      assert_statement
    | data_statement
    | goto_statement
    | let_statement )

/* ASSERT value [, error-message] */
assert_statement ::= 'ASSERT' arguments_2

/* DATA text */
data_statement ::= 'DATA' text

/* DIM A$(100) */
/* DIM A$(100,100) */
/* DIM A$(100,100,100) */
dim_statement ::= 'DIM' var

/* FOR var = start-value TO end-value STEP step-value */
for_statement ::= 'FOR' var _ '=' expression _ 'TO' expression (_ 'STEP' expression)?

/* GOTO line-number */
goto_statement ::= 'GOTO'? number

/* INPUT [# channel] [prompt ;] var [, var] ... */
input_statement ::= 'INPUT' channel prompt repeated_var 

/* LET var = value */
let_statement ::= 'LET'? var _ '=' expression

/* LIST start-line-number, end-line-number */
list_statement ::= 'LIST' arguments_2 

/* ON value GOTO line-number [, line_number] ... */
on_goto_statement ::= 'ON' expression1 _ 'GOTO' repeated_number

/* PRINT print-value */
print_statement ::= 'PRINT' channel print_expression

print_expression ::= print_separator* expression (print_separator+ expression?)?

print_separator ::= _ (',' | ';')

/* READ var [, var] ... */
read_statement ::= 'READ' repeated_var

/* REM text */
rem_statement ::= 'REM' text

arguments_1 ::= expression?

arguments_2 ::= (expression (_ ',' expression)?)?

arguments_3 ::= (expression (_ ',' expression (_ ',' expression)?)?)?

arguments_list ::=
    | expression (_ ',' expression)*

expression ::= primary_expression (op expression)*

primary_expression ::= number 
    | string
    | var
    | function
    | _ '(' expression _ ')'
    | unary_op primary_expression

function ::= _ (
      len_function
    | max_function
    | min_function )

/* LEN(string-value) */
len_function ::= 'LEN(' arguments_1 _ ')'

/* MAX(value, value) */
/* MIN(value, value) */
max_function ::= 'MAX(' arguments_2 _ ')'
min_function ::= 'MIN(' arguments_2 _ ')'

op ::= _ ('<=' | '>=' | '<>' | '<' | '>' | '=' | '+' | '-' | '*' | '/' | '^' | '&' | 'AND' | 'OR')

unary_op ::= _ ('-' | 'NOT')

repeated_number ::= number (_ ',' number)*

number ::= _ opt_sign ((digits decimal_digits?) | decimal_digits) ('E' opt_sign digits)
decimal_digits ::= ('.' opt_digits)
digits ::= digit+
opt_digits ::= digit*
opt_sign ::= sign?
digit ::= [0-9]
sign ::= [-]

repeated_var ::= var (_ ',' var)*

/* Note no space allowed before open paren */
var ::= _ letter (letter | digit | '_')* '$'? ('(' expression (',' expression)* ')')?

string ::= _ '"' ([^"] | '""')* '"' 

channel ::= _ ('#' number)?

prompt ::= (string _ ';')?

letter ::= [A-Z]

text ::= ' ' [#x20-#x7f]

_ ::= [ ]*
