; cc65 runtime
.include "zeropage.inc"
.import push1, pusha0, pushax

; sim65 vectors
.import _write, exit 

; Generated by linker
.import __MAIN_START__, __MAIN_SIZE__
.import __STACKSIZE__

; Export startup address to exehdr module
.export startup

message: .byte "Hello, world", $0A

.segment "STARTUP"

startup:
        cld                     ; Clear decimal flag
        ldx     #$FF
        txs                     ; Initialize the stack to $FF
        lda     #<(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        ldx     #>(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        sta     sp
        stx     sp+1            ; Set up C stack

        jsr     push1           ; Push file descriptor 1
        lda     #<message
        ldx     #>message
        jsr     pushax          ; Push message address
        lda     #13
        ldx     #0              ; Length into AX
        jsr     _write          ; Call write

        ldx     #$00
        lda     #$00
        jmp     exit            ; Return 0 from sim65
