.import getline, putline, putline_ptr1, putchar

; cc65 runtime
.include "zeropage.inc"
.import push1, pusha0, pushax

; sim65 vectors
.import _write, exit 

; Generated by linker
.import __MAIN_START__, __MAIN_SIZE__
.import __STACKSIZE__

; Export startup address to exehdr module
.export startup

message: .byte "Enter your name: "
message_length = * - message
hello: .byte "Hello, "
hello_length = * - hello

.segment "STARTUP"

startup:
        cld                     ; Clear decimal flag
        ldx     #$FF
        txs                     ; Initialize the stack to $FF
        lda     #<(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        ldx     #>(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        sta     sp
        stx     sp+1            ; Set up C stack

        lda     #<message       ; Load ptr1 with the message pointer
        sta     ptr1
        lda     #>message
        sta     ptr1+1
        lda     #message_length
        jsr     putline_ptr1    ; Write the message

        jsr     getline         ; Get the user's input
        pha                     ; Save the length of the input
        lda     #<hello         ; Load ptr1 with the hello pointer
        sta     ptr1
        lda     #>hello
        sta     ptr1+1
        lda     #hello_length
        jsr     putline_ptr1    ; Write "hello"
        pla                     ; Get input length
        jsr     putline         ; Output name (still in buffer)
        lda     #$0A            ; Linefeed
        jsr     putchar         ; Write linefeed

        ldx     #$00
        lda     #$00
        jmp     exit            ; Return 0 from sim65
