; cc65 runtime
.include "zeropage.inc"

; Generated by linker
.import __MAIN_START__, __MAIN_SIZE__
.import __BSS_RUN__, __BSS_SIZE__

.include "target.inc"
.include "basic.inc"

.zeropage

; A pointer to the current program line
line_ptr: .res 2

; The length of the current line
line_length: .res 1
; The curent line number; also used to store line number sought in find_line
line_number: .res 2

; A pointer to the start of the program
program_ptr: .res 2

; The start of the variable name table
variable_name_table_ptr: .res 2

; The start of the variable value table; maintained as the end of the variable name table
value_table_ptr: .res 2

; The start of the heap; reset to value_table_ptr plus the size of the value table when program is run
heap_ptr: .res 2

; The address of "high memory" that will not be touched by the interpreter
himem_ptr: .res 2

; The number of variables in the program.
variable_count: .res 1

.code

; Initializes a new program.
; Inserts an empty zero-length line -1 into the program space.

initialize_program:
        mvax    #(__BSS_RUN__ + __BSS_SIZE__), program_ptr
        stax    line_ptr                    ; Set program_ptr and line_ptr to end of BSS
        lda     #$FF                        ; Line number = -1
        ldy     #0                          
        sta     (line_ptr),y                ; Line number low byte
        iny     
        sta     (line_ptr),y                ; Line number high byte
        lda     #0      
        iny     
        sta     (line_ptr),y                ; Line length
        sta     variable_count              ; While we have 0 in A, set the number of variables
        jsr     get_line_start_plus_a       ; Adding header + A (0) to line_start gives variable_name_table_ptr in AX
        sta     variable_name_table_ptr
        stx     variable_name_table_ptr+1
        tay                                 ; Add 1 to variable_name_table_ptr for ending 0
        iny
        sty     value_table_ptr
        bne     @no_carry                   ; Low byte did not wrap around to 0
        inx                                 ; Increment high byte in X
@no_carry:
        stx     value_table_ptr+1           ; Save high byte
        ldy     #0                          ; Write index 0
        tya                                 ; Write 0
        sta     (variable_name_table_ptr),y ; Initialize variable name table to 0
        mvax    #(__MAIN_START__ + __MAIN_SIZE__), himem_ptr
        rts

; Sets line_ptr to program_ptr.
; X SAFE, Y SAFE

reset_line_ptr:
        mvaa    program_ptr, line_ptr
        rts

; Resets the program state. Zeros out the variable value table and initializes the heap.
; Invoked when the user modifies the program or invokes RUN or CLR commands.
; Returns carry clear on success or set on error (e.g., not enough memory to initialize program state)

reset_program:
        clc
        rts

; Searches for a line in the program.
; This function needs to be reasonably fast because it will be called every time the program executes GOTO, 
; GOSUB, RESTORE, or any other function that requires a line number.
; AX = the line number
; The find_line_sreg entry point uses the line number in sreg.
; Carry clear if ok (the was found), carry set if error (line not found).
; Sets line_ptr, line_number, and line_length if the line was found.
; If not found, line_ptr is left set to where the line would have been, i.e., pointing
; to the next-higher line.

find_line:
        stax    sreg
find_line_sreg:
        jsr     reset_line_ptr          ; Set line_ptr to beginning of program
next_line:      
        ldy     #1                      ; Set Y to 1 for getting high byte of line number
        lda     (line_ptr),y        
        cmp     sreg+1       
        bcc     @continue               ; Line number high byte is <target; go to next line
        bne     @return                 ; Return with carry set
        dey                             ; High byte is equal; decrement Y to 0
        lda     (line_ptr),y            ; Check the low byte of line number
        cmp     sreg                    ; Same logic for low byte
        bcc     @continue       
        beq     update_line_fields      ; Update line fields and return; otherwise return with carry bit set
@return:        
        rts     

@continue:      
        jsr     advance_line_ptr        ; Advance to the next line    
        jmp     next_line

; Advances the current line pointer to the next line. This is called from find_line so we don't set line_number
; or line_length or assume they've been set, because in find_line we want to scan the program as quickly as possible.
; line_ptr = current line (updated)
; Returns new line_ptr value in AX.

advance_line_ptr:
        ldy     #2                      ; Need offset 2 to get length
        lda     (line_ptr),y            ; Get length of current line
        jsr     get_line_start_plus_a
        stax    line_ptr                ; Store back into line_ptr
        rts

; Updates the line_number and line_length fields from line_ptr. 
; line_ptr = current line
; On return, line_number and line_length are set, and Y = 0.

update_line_fields:
        ldy     #2
        lda     (line_ptr),y            ; Get length of current line
        sta     line_length
        dey
        lda     (line_ptr),y            ; High byte of line number
        sta     line_number+1
        dey
        lda     (line_ptr),y            ; Low byte of line number
        sta     line_number
        clc                             ; In case we're wrapping up a function that clears carry on success
        rts

; Returns a pointer to the start of data for the current line (identified by line_ptr).
; The get_line_ptr_plus_a entry point adds whatever is in A to line_ptr.
; The get_line_start_plus_a entry point adds the size of the line header.
; Returns the pointer in AX.
; Y SAFE

get_line_start:
        lda     #0                      ; Add 0 extra bytes after header
get_line_start_plus_a:      
        clc     
        adc     #3                      ; Add 3 bytes for header
get_line_ptr_plus_a:        
        clc     
        adc     line_ptr                ; Add whatever's in A to line_ptr
        ldx     line_ptr+1
        bcc     @return
        inx
@return:
        rts

; TODO: figure out how much to grow/shrink before calling either function and call grow_ay first

; Delete program line, which must have previously been found with find_line.
; line_ptr = a pointer to the line to replace (previously set by find_line)
; On return, line_ptr retains the same value it had before, only it is now pointing to the next line.

delete_line:

; line_ptr points to a line that we have to remove.
; Find the next line and copy the reset of the program to where line_ptr is pointing now.
; There will always be a next line becasue we'll only be here if the line to delete
; actually exists.

        mva     line_ptr, copy_to_ptr   ; Current line_ptr will be the target of the memcpy
        pha                             ; Also push it on the stack so we can restore after advancing
        mva     line_ptr+1, copy_to_ptr+1   ; High byte
        pha
        jsr     advance_line_ptr        ; Move to line_ptr to next line (AX = line_ptr)
        stax    copy_from_ptr           ; This will be the source for the copy
        jsr     calculate_bytes_to_move ; Set copy_length to length of program from line_ptr
        jsr     update_pointers         ; Knowing copy from and to, we can update pointers
        jsr     copy_bytes              ; Compact the program
        pla                             ; line_ptr now points to an invalid line so restore saved value
        sta     line_ptr+1
        pla
        sta     line_ptr
        rts

; Inserts a new line, or does nothing if the line to insert is empty.
; line_ptr = a pointer to the insertion point (previously set by find_line)
; AX = the number of the new line (from find_line)
; output_buffer = the buffer holding the tokenized data
; w = the write position in output_buffer, which is the length of the data
; Returns carry clear on success, carry set on error.

insert_line:
        stax    sreg
insert_line_sreg:
        mvax    line_ptr, copy_from_ptr ; Initialize copy_from_ptr to line_ptr
        lda     w                       ; Load the length of the token data
        beq     @finish                 ; Line is empty
        pha                             ; Save the line length on the stack
        jsr     get_line_start_plus_a   ; Calculate destination address for current line
        stax    copy_to_ptr                
        jsr     calculate_bytes_to_move ; Set copy_length to length of program from line_ptr
        jsr     update_pointers         ; Knowing copy from and to, we can update pointers
        jsr     copy_bytes_back     
        lda     sreg                    ; Line number low byte     
        ldy     #0      
        sta     (line_ptr),y            ; Save line item number low byte
        lda     sreg+1                  ; Line number high byte
        iny     
        sta     (line_ptr),y            ; Save line item number high byte
        pla                             ; Get the line length saved earlier
        iny     
        sta     (line_ptr),y            ; Save line length
        ldx     #0
        stax    copy_length             ; Also save it into copy_length
        clc
        mvax    #output_buffer, copy_from_ptr   ; Source is output_buffer     
        jsr     get_line_start          ; Get destination address for copy
        stax    copy_to_ptr             ; Destination into copy_to_ptr
        jsr     copy_bytes              ; Copy data from buffer into program space
        jsr     advance_line_ptr        ; Jump over the new line

@finish:
        clc
        rts

; Calculates the bytes to move for both compact and expand as value_table_ptr - line_ptr.
; Returns the number of bytes in copy_length (borrowed from util.s)

calculate_bytes_to_move:
        sec                       
        lda     value_table_ptr
        sbc     line_ptr
        sta     copy_length             ; Store length
        lda     value_table_ptr+1      
        sbc     line_ptr+1      
        sta     copy_length+1           ; Store high byte of length
        rts

; Updates variable_name_table_ptr and value_table_ptr by adding (copy_to_ptr - copy_from_ptr).
; In other words, if we're moving everything to a higher address (copy_to_ptr > copy_from_ptr), then we have
; to move the pointers up too, and vice versa. We're just shifting the pointers by however many bytes
; we moved the end of the program.
; Uses XY to store the difference value.

update_pointers:
        sec           
        lda     copy_to_ptr
        sbc     copy_from_ptr
        tax                             ; Difference low byte in X
        lda     copy_to_ptr+1       
        sbc     copy_from_ptr+1     
        tay                             ; Difference high byte in Y
        clc                             ; Update variable_name_table_ptr
        txa                             
        adc     variable_name_table_ptr
        sta     variable_name_table_ptr
        tya
        adc     variable_name_table_ptr+1
        sta     variable_name_table_ptr+1
        clc                             ; Update value_table_ptr
        txa                      
        adc     value_table_ptr
        sta     value_table_ptr
        tya
        adc     value_table_ptr+1
        sta     value_table_ptr+1
        rts

; Tries to increase value_table_ptr by an amount.
; A (check_grow_a) or AY (check_grow_ay) = the value to add to value_table_ptr
; Returns carry clear if the add was successful, otherwise carry set.

grow_a:
        ldy     #0
grow_ay:

@candidate_ptr = ptr1

        clc
        adc     value_table_ptr
        tax                             ; Save low byte in X
        tya                             ; Add high byte
        adc     value_table_ptr+1
        bcs     @done                   ; Pointer wrapped around
        stx     @candidate_ptr          ; Save calculated pointer since check_himem will clobber it
        sta     @candidate_ptr+1
        jsr     check_himem
        bcs     @done
        mvax    @candidate_ptr, value_table_ptr ; Validation successful; copy candidate_ptr into value_table_ptr
@done:
        rts

; Fall through to check_himem.

; Checks if a pointer is > himem_ptr.
; Returns carry clear if the pointer is <=himem_ptr, carry set if it is greater.
; XA = the pointer to test (NOTE A IS HIGH BYTE AND X IS LOW BYTE)
; Y SAFE

check_himem:
        cmp     himem_ptr+1
        bcc     @done                   ; argument high byte < himem_ptr high byte
        bne     @done                   ; argument high byte > himem_ptr high byte (carry is set)
        txa                             ; High bytes are equal; compare low bytes
        cmp     himem_ptr
        bcc     @done                   ; argument low byte < himem_ptr low byte
        bne     @done                   ; argument low byte > himem_ptr low byte (carry is set)
        clc                             ; Pointers are equal; clear carry since this is success
@done:
        rts
