; cc65 runtime
.include "zeropage.inc"
.import push1, pusha0, pushax

; sim65 vectors
.import _write, exit 

; Generated by linker
.import __MAIN_START__, __MAIN_SIZE__
.import __STACKSIZE__

.include "basic.inc"

.segment "STARTUP"

message: .byte "Enter your name: "
message_length = * - message
hello: .byte "Hello, "
hello_length = * - hello

startup:
.export startup
        cld                             ; Clear decimal flag
        ldx     #$FF        
        txs                             ; Initialize the stack to $FF
        lda     #<(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        ldx     #>(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        sta     sp
        stx     sp+1                    ; Set up C stack

        jmp     main
