; cc65 runtime
.importzp sp

; sim65 vectors
.import exit

; Generated by linker
.import __MAIN_START__, __MAIN_SIZE__
.import __STACKSIZE__

.import buffer, buffer_length
.import readline, write, newline

.segment "STARTUP"

message: .byte "Enter your name: "
message_length = * - message
hello: .byte "Hello, "
hello_length = * - hello

startup:
.export startup
        cld                             ; Clear decimal flag
        ldx     #$FF        
        txs                             ; Initialize the stack to $FF
        lda     #<(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        ldx     #>(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        sta     sp
        stx     sp+1                    ; Set up C stack
        
        lda     #<message               ; Print message
        ldx     #>message       
        ldy     #message_length     
        jsr     write                   ; Write the message
        
        jsr     readline                ; Get the user's input
        lda     #<hello                 ; Load AX with the hello pointer
        ldx     #>hello     
        ldy     #hello_length       
        jsr     write                   ; Write "hello"
        lda     #<buffer
        ldx     #>buffer
        ldy     buffer_length
        jsr     write                   ; Output name (still in buffer)
        jsr     newline                 ; Write linefeed
        ldx     #$00        
        lda     #$00        
        jmp     exit                    ; Return 0 from sim65
