;
; File generated by cc65 v 2.19 - Git 034f73a9e
;
	.fopt		compiler,"cc65 v 2.19 - Git 034f73a9e"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "tests/decode_test.c", 5630, 1767135305
	.dbg		file, "tests/test.h", 8355, 1768147025
	.dbg		file, "/usr/local/share/cc65/include/assert.h", 3002, 1768078665
	.dbg		file, "/usr/local/share/cc65/include/stdio.h", 6999, 1768078665
	.dbg		file, "/usr/local/share/cc65/include/string.h", 5678, 1768078665
	.dbg		file, "/usr/local/share/cc65/include/ctype.h", 4485, 1768078665
	.dbg		file, "/usr/local/share/cc65/include/stddef.h", 3037, 1768078665
	.dbg		file, "tests/../constants.h", 3560, 1768148759
	.dbg		file, "tests/../zeropage.h", 5631, 1768148759
	.forceimport	__STARTUP__
	.dbg		sym, "stderr", "00", extern, "_stderr"
	.dbg		sym, "line_ptr", "00", extern, "_line_ptr"
	.dbg		sym, "string_ptr", "00", extern, "_string_ptr"
	.dbg		sym, "line_pos", "00", extern, "_line_pos"
	.dbg		sym, "decode_name_ptr", "00", extern, "_decode_name_ptr"
	.dbg		sym, "decode_name_length", "00", extern, "_decode_name_length"
	.dbg		sym, "decode_name_type", "00", extern, "_decode_name_type"
	.dbg		sym, "decode_name_arity", "00", extern, "_decode_name_arity"
	.dbg		sym, "line_buffer", "00", extern, "_line_buffer"
	.import		___afailed
	.import		_stderr
	.import		_fprintf
	.import		_fputc
	.import		_fputs
	.import		_printf
	.import		_strlen
	.import		_memcmp
	.import		_memcpy
	.import		_isprint
	.importzp	_line_ptr
	.importzp	_string_ptr
	.importzp	_line_pos
	.importzp	_decode_name_ptr
	.importzp	_decode_name_length
	.importzp	_decode_name_type
	.importzp	_decode_name_arity
	.import		_line_buffer
	.import		_decode_expression
	.import		_decode_number
	.import		_decode_string
	.import		_decode_name
	.import		_decode_byte
	.import		_store_fp0
	.import		_initialize_target
	.import		_initialize_program
	.export		_hexdump
	.export		_set_line
	.export		_parse_and_decode_name
	.export		_test_decode_byte
	.export		_test_decode_number
	.export		_test_decode_string
	.export		_test_decode_name
	.export		_decode_xh_vectors
	.export		_unary_op_count
	.export		_xh_unary_operator
	.export		_op_count
	.export		_xh_operator
	.export		_num_count
	.export		_xh_number
	.export		_xh_string
	.export		_var_count
	.export		_xh_variable
	.export		_function_count
	.export		_xh_function
	.export		_paren_count
	.export		_xh_paren
	.export		_test_decode_expression
	.export		_main

.segment	"DATA"

_decode_xh_vectors:
	.addr	_xh_unary_operator-1
	.addr	_xh_operator-1
	.addr	_xh_number-1
	.addr	_xh_string-1
	.addr	_xh_variable-1
	.addr	_xh_function-1
	.addr	_xh_paren-1

.segment	"RODATA"

S010D:
	.byte	$20,$20,$25,$73,$3A,$25,$75,$3A,$20,$61,$73,$73,$65,$72,$74,$20
	.byte	$25,$73,$20,$28,$25,$6C,$64,$2C,$20,$24,$25,$6C,$58,$29,$20,$25
	.byte	$73,$20,$25,$73,$20,$28,$25,$6C,$64,$2C,$20,$24,$25,$6C,$58,$29
	.byte	$3A,$20,$00
S011B	:=	S010D+0
S0106	:=	S010D+0
S0122	:=	S010D+0
S00FF	:=	S010D+0
S0044	:=	S010D+0
S0129	:=	S010D+0
S00F1	:=	S010D+0
S0130	:=	S010D+0
S00EA	:=	S010D+0
S0137	:=	S010D+0
S00E3	:=	S010D+0
S01A9	:=	S010D+0
S013E	:=	S010D+0
S00D5	:=	S010D+0
S0145	:=	S010D+0
S00CE	:=	S010D+0
S014C	:=	S010D+0
S00C7	:=	S010D+0
S0153	:=	S010D+0
S004B	:=	S010D+0
S015A	:=	S010D+0
S00B9	:=	S010D+0
S0161	:=	S010D+0
S00B2	:=	S010D+0
S00AB	:=	S010D+0
S0168	:=	S010D+0
S0052	:=	S010D+0
S016F	:=	S010D+0
S009B	:=	S010D+0
S0176	:=	S010D+0
S0091	:=	S010D+0
S01A2	:=	S010D+0
S017D	:=	S010D+0
S008A	:=	S010D+0
S007E	:=	S010D+0
S0184	:=	S010D+0
S0077	:=	S010D+0
S0070	:=	S010D+0
S018D	:=	S010D+0
S0069	:=	S010D+0
S0194	:=	S010D+0
S0062	:=	S010D+0
S005B	:=	S010D+0
S019B	:=	S010D+0
S01B0	:=	S010D+0
S00C0:
	.byte	$20,$20,$25,$73,$3A,$25,$75,$3A,$20,$61,$73,$73,$65,$72,$74,$20
	.byte	$25,$73,$20,$28,$24,$25,$30,$34,$58,$29,$20,$25,$73,$20,$25,$73
	.byte	$20,$28,$24,$25,$30,$34,$58,$29,$3A,$20,$00
S00DC	:=	S00C0+0
S00F8	:=	S00C0+0
S00A4	:=	S00C0+0
S0114	:=	S00C0+0
S0093:
	.byte	$6D,$65,$6D,$63,$6D,$70,$28,$73,$74,$72,$69,$6E,$67,$5F,$70,$74
	.byte	$72,$2D,$3E,$64,$61,$74,$61,$2C,$20,$22,$48,$45,$4C,$4C,$4F,$22
	.byte	$2C,$20,$35,$29,$00
S0118:
	.byte	$6C,$69,$6E,$65,$5F,$62,$75,$66,$66,$65,$72,$2E,$64,$61,$74,$61
	.byte	$20,$2B,$20,$31,$31,$00
S018C:
	.byte	$74,$65,$73,$74,$5F,$64,$65,$63,$6F,$64,$65,$5F,$65,$78,$70,$72
	.byte	$65,$73,$73,$69,$6F,$6E
S00FC:
	.byte	$6C,$69,$6E,$65,$5F,$62,$75,$66,$66,$65,$72,$2E,$64,$61,$74,$61
	.byte	$20,$2B,$20,$39,$00
S003C:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$25,$73,$20,$28,$24,$25,$30,$34
	.byte	$58,$29,$3A,$0A,$00
S00E0:
	.byte	$6C,$69,$6E,$65,$5F,$62,$75,$66,$66,$65,$72,$2E,$64,$61,$74,$61
	.byte	$20,$2B,$20,$37,$00
S00C4:
	.byte	$6C,$69,$6E,$65,$5F,$62,$75,$66,$66,$65,$72,$2E,$64,$61,$74,$61
	.byte	$20,$2B,$20,$31,$00
S0057:
	.byte	$74,$65,$73,$74,$73,$2F,$64,$65,$63,$6F,$64,$65,$5F,$74,$65,$73
	.byte	$74,$2E,$63,$00
S019C	:=	S0057+0
S01AA	:=	S0057+0
S013C	:=	S0057+0
S00E1	:=	S0057+0
S005C	:=	S0057+0
S011C	:=	S0057+0
S0199	:=	S0057+0
S00DD	:=	S0057+0
S0060	:=	S0057+0
S0195	:=	S0057+0
S0049	:=	S0057+0
S0063	:=	S0057+0
S0107	:=	S0057+0
S0138	:=	S0057+0
S0045	:=	S0057+0
S0067	:=	S0057+0
S0192	:=	S0057+0
S010B	:=	S0057+0
S006A	:=	S0057+0
S0104	:=	S0057+0
S018E	:=	S0057+0
S0120	:=	S0057+0
S006E	:=	S0057+0
S00E4	:=	S0057+0
S01AE	:=	S0057+0
S0071	:=	S0057+0
S0053	:=	S0057+0
S010E	:=	S0057+0
S0100	:=	S0057+0
S0075	:=	S0057+0
S0189	:=	S0057+0
S0078	:=	S0057+0
S0123	:=	S0057+0
S0185	:=	S0057+0
S00FD	:=	S0057+0
S007C	:=	S0057+0
S00DA	:=	S0057+0
S01B1	:=	S0057+0
S007F	:=	S0057+0
S01A3	:=	S0057+0
S0182	:=	S0057+0
S013F	:=	S0057+0
S0083	:=	S0057+0
S0143	:=	S0057+0
S00D6	:=	S0057+0
S0135	:=	S0057+0
S00F9	:=	S0057+0
S017E	:=	S0057+0
S0127	:=	S0057+0
S00D3	:=	S0057+0
S008B	:=	S0057+0
S0146	:=	S0057+0
S0050	:=	S0057+0
S017B	:=	S0057+0
S008F	:=	S0057+0
S00F6	:=	S0057+0
S014A	:=	S0057+0
S0092	:=	S0057+0
S01B5	:=	S0057+0
S00CF	:=	S0057+0
S0177	:=	S0057+0
S003D:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$25,$30,$34,$58,$20,$25,$30,$34
	.byte	$58,$20,$20,$00
S0174	:=	S0057+0
S012A	:=	S0057+0
S0099	:=	S0057+0
S01A7	:=	S0057+0
S009C	:=	S0057+0
S0170	:=	S0057+0
S0112	:=	S0057+0
S016D	:=	S0057+0
S00A0	:=	S0057+0
S00F2	:=	S0057+0
S00CC	:=	S0057+0
S014D	:=	S0057+0
S0115	:=	S0057+0
S00A5	:=	S0057+0
S0151	:=	S0057+0
S0169	:=	S0057+0
S00C8	:=	S0057+0
S00A9	:=	S0057+0
S00E8	:=	S0057+0
S0131	:=	S0057+0
S00AC	:=	S0057+0
S0119	:=	S0057+0
S0166	:=	S0057+0
S00C5	:=	S0057+0
S00B0	:=	S0057+0
S00EF	:=	S0057+0
S00EB	:=	S0057+0
S00B3	:=	S0057+0
S01A0	:=	S0057+0
S0162	:=	S0057+0
S0154	:=	S0057+0
S00B7	:=	S0057+0
S015F	:=	S0057+0
S00BA	:=	S0057+0
S00C1	:=	S0057+0
S015B	:=	S0057+0
S00BE	:=	S0057+0
S0158	:=	S0057+0
S004C	:=	S0057+0
S012E	:=	S0057+0
S00E5:
	.byte	$64,$65,$63,$6F,$64,$65,$5F,$6E,$61,$6D,$65,$5F,$6C,$65,$6E,$67
	.byte	$74,$68,$00
S008C:
	.byte	$73,$74,$72,$69,$6E,$67,$5F,$70,$74,$72,$2D,$3E,$6C,$65,$6E,$67
	.byte	$74,$68,$00
S0101	:=	S00E5+0
S011D	:=	S00E5+0
S00AD	:=	S00E5+0
S00C9	:=	S00E5+0
S005A:
	.byte	$74,$65,$73,$74,$5F,$64,$65,$63,$6F,$64,$65,$5F,$6E,$75,$6D,$62
	.byte	$65,$72
S012B:
	.byte	$64,$65,$63,$6F,$64,$65,$5F,$6E,$61,$6D,$65,$5F,$61,$72,$69,$74
	.byte	$79,$00
S00F3	:=	S012B+0
S00D7	:=	S012B+0
S010F	:=	S012B+0
S0086:
	.byte	$74,$65,$73,$74,$5F,$64,$65,$63,$6F,$64,$65,$5F,$73,$74,$72,$69
	.byte	$6E,$67
S00BB	:=	S012B+0
S00D0:
	.byte	$64,$65,$63,$6F,$64,$65,$5F,$6E,$61,$6D,$65,$5F,$74,$79,$70,$65
	.byte	$00
S00EC	:=	S00D0+0
S0124	:=	S00D0+0
S00B4	:=	S00D0+0
S0108	:=	S00D0+0
S00A8:
	.byte	$6C,$69,$6E,$65,$5F,$62,$75,$66,$66,$65,$72,$2E,$64,$61,$74,$61
	.byte	$00
S017F:
	.byte	$2A,$64,$65,$63,$6F,$64,$65,$5F,$6E,$61,$6D,$65,$5F,$70,$74,$72
	.byte	$00
S00FA	:=	S017F+1
S0116	:=	S017F+1
S00DE	:=	S017F+1
S00A3:
	.byte	$74,$65,$73,$74,$5F,$64,$65,$63,$6F,$64,$65,$5F,$6E,$61,$6D,$65
S0043:
	.byte	$74,$65,$73,$74,$5F,$64,$65,$63,$6F,$64,$65,$5F,$62,$79,$74,$65
S00C2	:=	S017F+1
S00A6	:=	S017F+1
S01AB:
	.byte	$66,$75,$6E,$63,$74,$69,$6F,$6E,$5F,$63,$6F,$75,$6E,$74,$00
S01A4:
	.byte	$75,$6E,$61,$72,$79,$5F,$6F,$70,$5F,$63,$6F,$75,$6E,$74,$00
S0165:
	.byte	$28,$72,$65,$73,$75,$6C,$74,$5F,$31,$29,$2E,$65,$00
S016C:
	.byte	$28,$72,$65,$73,$75,$6C,$74,$5F,$31,$29,$2E,$74,$00
S0173:
	.byte	$28,$72,$65,$73,$75,$6C,$74,$5F,$32,$29,$2E,$65,$00
S017A:
	.byte	$28,$72,$65,$73,$75,$6C,$74,$5F,$32,$29,$2E,$74,$00
S005F	:=	S0165+0
S0087:
	.byte	$26,$6C,$69,$6E,$65,$5F,$62,$75,$66,$66,$65,$72,$00
S0066	:=	S016C+0
S0082:
	.byte	$28,$72,$65,$73,$75,$6C,$74,$5F,$33,$29,$2E,$74,$00
S006D	:=	S0173+0
S007B:
	.byte	$28,$72,$65,$73,$75,$6C,$74,$5F,$33,$29,$2E,$65,$00
S0074	:=	S017A+0
S01B2:
	.byte	$70,$61,$72,$65,$6E,$5F,$63,$6F,$75,$6E,$74,$00
S0080:
	.byte	$28,$72,$65,$73,$75,$6C,$74,$29,$2E,$74,$00
S006B:
	.byte	$28,$72,$65,$73,$75,$6C,$74,$29,$2E,$65,$00
S0181:
	.byte	$27,$58,$27,$20,$7C,$20,$30,$78,$38,$30,$00
S0064	:=	S0080+0
S0089:
	.byte	$73,$74,$72,$69,$6E,$67,$5F,$70,$74,$72,$00
S005D	:=	S006B+0
S0054:
	.byte	$62,$79,$74,$65,$5F,$76,$61,$6C,$75,$65,$00
S004D	:=	S0054+0
S0178	:=	S0080+0
S0046	:=	S0054+0
S0171	:=	S006B+0
S0079	:=	S006B+0
S016A	:=	S0080+0
S0072	:=	S0080+0
S0163	:=	S006B+0
S0196:
	.byte	$76,$61,$72,$5F,$63,$6F,$75,$6E,$74,$00
S018F:
	.byte	$6E,$75,$6D,$5F,$63,$6F,$75,$6E,$74,$00
S009D:
	.byte	$6C,$69,$6E,$65,$5F,$70,$6F,$73,$00
S0186:
	.byte	$66,$75,$6E,$63,$74,$69,$6F,$6E,$00
S0088:
	.byte	$6C,$69,$6E,$65,$5F,$70,$74,$72,$00
S019D	:=	S01A4+6
S0094:
	.byte	$48,$45,$4C,$4C,$4F,$00
S0095	:=	S0094+0
S0098	:=	S0094+0
S003E:
	.byte	$25,$30,$32,$58,$20,$00
S0085:
	.byte	$25,$73,$3A,$0A,$00
S00D2:
	.byte	$30,$78,$30,$30,$00
S0042	:=	S0085+0
S018B	:=	S0085+0
S004F:
	.byte	$30,$78,$30,$31,$00
S0048	:=	S00D2+0
S0126	:=	S004F+0
S00A2	:=	S0085+0
S0059	:=	S0085+0
S00EE	:=	S004F+0
S0056:
	.byte	$30,$78,$30,$33,$00
S010A	:=	S00D2+0
S00B6	:=	S00D2+0
S0058:
	.byte	$4F,$4B,$0A,$00
S01A1	:=	S0058+0
S012F	:=	S0058+0
S0128	:=	S0058+0
S00E9	:=	S0058+0
S019A	:=	S0058+0
S00F7	:=	S0058+0
S0061	:=	S0058+0
S0193	:=	S0058+0
S0136	:=	S0058+0
S0068	:=	S0058+0
S00E2	:=	S0058+0
S0051	:=	S0058+0
S006F	:=	S0058+0
S00FE	:=	S0058+0
S018A	:=	S0058+0
S013D	:=	S0058+0
S00DB	:=	S0058+0
S0076	:=	S0058+0
S01A8	:=	S0058+0
S007D	:=	S0058+0
S0183	:=	S0058+0
S0084	:=	S0058+0
S0144	:=	S0058+0
S00D4	:=	S0058+0
S0121	:=	S0058+0
S004A	:=	S0058+0
S0105	:=	S0058+0
S017C	:=	S0058+0
S0090	:=	S0058+0
S014B	:=	S0058+0
S00CD	:=	S0058+0
S01AF	:=	S0058+0
S011A	:=	S0058+0
S0175	:=	S0058+0
S010C	:=	S0058+0
S009A	:=	S0058+0
S0152	:=	S0058+0
S00C6	:=	S0058+0
S003F:
	.byte	$20,$20,$20,$00
S016E	:=	S0058+0
S00A1	:=	S0058+0
S01B6	:=	S0058+0
S00BF	:=	S0058+0
S0159	:=	S0058+0
S00AA	:=	S0058+0
S0167	:=	S0058+0
S00B1	:=	S0058+0
S00F0	:=	S0058+0
S0160	:=	S0058+0
S00B8	:=	S0058+0
S0113	:=	S0058+0
S015D:
	.byte	$3D,$3D,$00
S00B5	:=	S015D+0
S015C:
	.byte	$6F,$70,$00
S0164	:=	S015D+0
S0117	:=	S015D+0
S00AE	:=	S015D+0
S00BC	:=	S015D+0
S01B3	:=	S015D+0
S00A7	:=	S015D+0
S0157:
	.byte	$31,$33,$00
S016B	:=	S015D+0
S0156	:=	S015D+0
S009F:
	.byte	$31,$30,$00
S0155	:=	S015C+0
S009E	:=	S015D+0
S00C3	:=	S015D+0
S00CA	:=	S015D+0
S0172	:=	S015D+0
S0110	:=	S015D+0
S0109	:=	S015D+0
S014F	:=	S015D+0
S0096	:=	S015D+0
S014E	:=	S015C+0
S011E	:=	S015D+0
S0179	:=	S015D+0
S00D1	:=	S015D+0
S01AC	:=	S015D+0
S0047	:=	S015D+0
S008D	:=	S015D+0
S0148	:=	S015D+0
S0147	:=	S015C+0
S0180	:=	S015D+0
S00D8	:=	S015D+0
S0081	:=	S015D+0
S0102	:=	S015D+0
S0141	:=	S015D+0
S007A	:=	S015D+0
S0140	:=	S015C+0
S0187	:=	S015D+0
S004E	:=	S015D+0
S01A5	:=	S015D+0
S00DF	:=	S015D+0
S00FB	:=	S015D+0
S0073	:=	S015D+0
S013A	:=	S015D+0
S006C	:=	S015D+0
S0139	:=	S015C+0
S0190	:=	S015D+0
S0125	:=	S015D+0
S00E6	:=	S015D+0
S0055	:=	S015D+0
S0065	:=	S015D+0
S00F4	:=	S015D+0
S0133	:=	S015D+0
S0197	:=	S015D+0
S019E	:=	S015D+0
S005E	:=	S015D+0
S0132	:=	S015C+0
S00ED	:=	S015D+0
S012D:
	.byte	$2D,$31,$00
S012C	:=	S015D+0
S0111	:=	S012D+0
S019F:
	.byte	$35,$00
S0134	:=	S0181+9
S00F5	:=	S0181+9
S00E7:
	.byte	$32,$00
S0191	:=	S00E7+0
S013B	:=	S0118+20
S00D9	:=	S0181+9
S01A6	:=	S00E7+0
S0188	:=	S0181+9
S0142	:=	S0181+9
S0103	:=	S0118+20
S011F	:=	S00E7+0
S0149	:=	S0056+3
S008E	:=	S019F+0
S01AD	:=	S0118+20
S00CB:
	.byte	$36,$00
S0097	:=	S0181+9
S0041	:=	S003C+19
S0040	:=	S010D+49
S0150	:=	S00E7+0
S00BD	:=	S0181+9
S01B4	:=	S0118+20
S00AF	:=	S0118+20
S0198	:=	S0056+3
S015E	:=	S0118+20

.segment	"BSS"

_unary_op_count:
	.res	2,$00
_op_count:
	.res	2,$00
_num_count:
	.res	2,$00
_var_count:
	.res	2,$00
_function_count:
	.res	2,$00
_paren_count:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ hexdump (const char *name, const char *data, unsigned int length)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hexdump: near

	.dbg	func, "hexdump", "00", static, "_hexdump"
	.dbg	sym, "name", "00", auto, 4
	.dbg	sym, "data", "00", auto, 2
	.dbg	sym, "length", "00", auto, 0
	.dbg	sym, "i", "00", auto, -2
	.dbg	sym, "j", "00", auto, -4
	.dbg	sym, "p", "00", auto, -6

.segment	"CODE"

	.dbg	line, "tests/test.h", 225
	jsr     pushax
	.dbg	line, "tests/test.h", 228
	jsr     decsp6
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S003C)
	ldx     #>(S003C)
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     pushax
	ldy     #$08
	jsr     _fprintf
	.dbg	line, "tests/test.h", 229
	ldx     #$00
	lda     #$00
	ldy     #$04
	jsr     staxysp
L0002:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     tosultax
	jne     L0005
	jmp     L0003
	.dbg	line, "tests/test.h", 230
L0005:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S003D)
	ldx     #>(S003D)
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	ldy     #$08
	jsr     _fprintf
	.dbg	line, "tests/test.h", 231
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$00
	jsr     staxysp
	.dbg	line, "tests/test.h", 232
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
L0006:	ldy     #$03
	jsr     ldaxysp
	cpx     #$00
	bne     L000A
	cmp     #$10
L000A:	jsr     boolult
	jne     L0009
	jmp     L0007
	.dbg	line, "tests/test.h", 233
L0009:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     tosultax
	jeq     L000B
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S003E)
	ldx     #>(S003E)
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/test.h", 234
	jmp     L0008
L000B:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S003F)
	ldx     #>(S003F)
	jsr     pushax
	ldy     #$04
	jsr     _fprintf
	.dbg	line, "tests/test.h", 232
L0008:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0006
	.dbg	line, "tests/test.h", 236
L0007:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0040)
	ldx     #>(S0040)
	jsr     pushax
	ldy     #$04
	jsr     _fprintf
	.dbg	line, "tests/test.h", 237
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$00
	jsr     staxysp
	.dbg	line, "tests/test.h", 238
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
L000D:	ldy     #$03
	jsr     ldaxysp
	cpx     #$00
	bne     L0011
	cmp     #$10
L0011:	jsr     boolult
	jne     L0010
	jmp     L000E
	.dbg	line, "tests/test.h", 239
L0010:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     tosultax
	jeq     L0012
	ldy     #$01
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     _isprint
	stx     tmp1
	ora     tmp1
	jeq     L0013
	ldy     #$01
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jmp     L0014
L0013:	ldx     #$00
	lda     #$2E
L0014:	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputc
	.dbg	line, "tests/test.h", 240
	jmp     L000F
L0012:	ldx     #$00
	lda     #$20
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputc
	.dbg	line, "tests/test.h", 238
L000F:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L000D
	.dbg	line, "tests/test.h", 242
L000E:	lda     #<(S0041)
	ldx     #>(S0041)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	.dbg	line, "tests/test.h", 229
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	jsr     addeqysp
	jmp     L0002
	.dbg	line, "tests/test.h", 244
L0003:	ldy     #$0C
	jsr     addysp
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ set_line (int line, const char *data, unsigned int length)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_line: near

	.dbg	func, "set_line", "00", static, "_set_line"
	.dbg	sym, "line", "00", auto, 4
	.dbg	sym, "data", "00", auto, 2
	.dbg	sym, "length", "00", auto, 0

.segment	"CODE"

	.dbg	line, "tests/test.h", 246
	jsr     pushax
	.dbg	line, "tests/test.h", 247
	ldy     #$05
	jsr     ldaxysp
	sta     _line_buffer+1
	stx     _line_buffer+1+1
	.dbg	line, "tests/test.h", 248
	ldy     #$01
	jsr     ldaxysp
	jsr     incax3
	ldx     #$00
	sta     _line_buffer
	.dbg	line, "tests/test.h", 249
	lda     #<(_line_buffer+3)
	ldx     #>(_line_buffer+3)
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     _memcpy
	.dbg	line, "tests/test.h", 250
	lda     #<(_line_buffer)
	ldx     #>(_line_buffer)
	sta     _line_ptr
	stx     _line_ptr+1
	.dbg	line, "tests/test.h", 251
	ldx     #$00
	lda     #$03
	sta     _line_pos
	.dbg	line, "tests/test.h", 252
	jsr     incsp6
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ parse_and_decode_name (const char *name)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_parse_and_decode_name: near

	.dbg	func, "parse_and_decode_name", "00", static, "_parse_and_decode_name"
	.dbg	sym, "name", "00", auto, 0
	.dbg	sym, "length", "00", auto, -2

.segment	"CODE"

	.dbg	line, "tests/test.h", 254
	jsr     pushax
	.dbg	line, "tests/test.h", 257
	ldy     #$01
	jsr     ldaxysp
	jsr     _strlen
	jsr     pushax
	.dbg	line, "tests/test.h", 258
	lda     #<(_line_buffer+3)
	ldx     #>(_line_buffer+3)
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     _memcpy
	.dbg	line, "tests/test.h", 259
	ldy     #$01
	jsr     ldaxysp
	jsr     decax1
	clc
	adc     #<(_line_buffer+3)
	tay
	txa
	adc     #>(_line_buffer+3)
	tax
	tya
	jsr     pushax
	ldy     #$00
	jsr     ldauidx
	ora     #$80
	ldy     #$00
	jsr     staspidx
	.dbg	line, "tests/test.h", 260
	lda     #<(_line_buffer)
	ldx     #>(_line_buffer)
	sta     _line_ptr
	stx     _line_ptr+1
	.dbg	line, "tests/test.h", 261
	ldx     #$00
	lda     #$03
	sta     _line_pos
	.dbg	line, "tests/test.h", 262
	jsr     _decode_name
	.dbg	line, "tests/test.h", 263
	jsr     incsp4
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ test_decode_byte (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_decode_byte: near

	.dbg	func, "test_decode_byte", "00", static, "_test_decode_byte"
	.dbg	sym, "byte_value", "00", auto, -1
	.dbg	sym, "line_data", "00", auto, -4

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 7
	jsr     decsp4
	ldy     #$02
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/decode_test.c", 9
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0042)
	ldx     #>(S0042)
	jsr     pushax
	lda     #<(S0043)
	ldx     #>(S0043)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/decode_test.c", 11
	ldx     #$00
	lda     #$00
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$03
	jsr     _set_line
	.dbg	line, "tests/decode_test.c", 13
	jsr     _decode_byte
	ldy     #$03
	sta     (c_sp),y
	.dbg	line, "tests/decode_test.c", 14
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0044)
	ldx     #>(S0044)
	jsr     pushax
	lda     #<(S0045)
	ldx     #>(S0045)
	jsr     pushax
	ldx     #$00
	lda     #$0E
	jsr     pushax
	lda     #<(S0046)
	ldx     #>(S0046)
	jsr     pushax
	ldy     #$0D
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$11
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S0047)
	ldx     #>(S0047)
	jsr     pushax
	lda     #<(S0048)
	ldx     #>(S0048)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	cmp     #$00
	jsr     booleq
	jeq     L0006
	jmp     L0007
L0006:	lda     #<(S0049)
	ldx     #>(S0049)
	jsr     pushax
	ldx     #$00
	lda     #$0E
	jsr     ___afailed
L0007:	lda     #<(S004A)
	ldx     #>(S004A)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 16
	jsr     _decode_byte
	ldy     #$03
	sta     (c_sp),y
	.dbg	line, "tests/decode_test.c", 17
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S004B)
	ldx     #>(S004B)
	jsr     pushax
	lda     #<(S004C)
	ldx     #>(S004C)
	jsr     pushax
	ldx     #$00
	lda     #$11
	jsr     pushax
	lda     #<(S004D)
	ldx     #>(S004D)
	jsr     pushax
	ldy     #$0D
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$11
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S004E)
	ldx     #>(S004E)
	jsr     pushax
	lda     #<(S004F)
	ldx     #>(S004F)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	cmp     #$01
	jsr     booleq
	jeq     L000B
	jmp     L000C
L000B:	lda     #<(S0050)
	ldx     #>(S0050)
	jsr     pushax
	ldx     #$00
	lda     #$11
	jsr     ___afailed
L000C:	lda     #<(S0051)
	ldx     #>(S0051)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 19
	jsr     _decode_byte
	ldy     #$03
	sta     (c_sp),y
	.dbg	line, "tests/decode_test.c", 20
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0052)
	ldx     #>(S0052)
	jsr     pushax
	lda     #<(S0053)
	ldx     #>(S0053)
	jsr     pushax
	ldx     #$00
	lda     #$14
	jsr     pushax
	lda     #<(S0054)
	ldx     #>(S0054)
	jsr     pushax
	ldy     #$0D
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$11
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S0055)
	ldx     #>(S0055)
	jsr     pushax
	lda     #<(S0056)
	ldx     #>(S0056)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$03
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$03
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	cmp     #$03
	jsr     booleq
	jeq     L0010
	jmp     L0011
L0010:	lda     #<(S0057)
	ldx     #>(S0057)
	jsr     pushax
	ldx     #$00
	lda     #$14
	jsr     ___afailed
L0011:	lda     #<(S0058)
	ldx     #>(S0058)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 21
	jsr     incsp4
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$00
	.byte	$01
	.byte	$03

.endproc

; ---------------------------------------------------------------
; void __near__ test_decode_number (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_decode_number: near

	.dbg	func, "test_decode_number", "00", static, "_test_decode_number"
	.dbg	sym, "line_data", "00", auto, -17
	.dbg	sym, "result_1", "00", auto, -22
	.dbg	sym, "result_2", "00", auto, -27
	.dbg	sym, "result_3", "00", auto, -32
	.dbg	sym, "result", "00", auto, -37

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 24
	ldy     #$11
	jsr     subysp
	ldy     #$10
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/decode_test.c", 25
	jsr     decsp5
	ldy     #$04
L0003:	lda     M0002,y
	sta     (c_sp),y
	dey
	bpl     L0003
	.dbg	line, "tests/decode_test.c", 26
	jsr     decsp5
	ldy     #$04
L0004:	lda     M0003,y
	sta     (c_sp),y
	dey
	bpl     L0004
	.dbg	line, "tests/decode_test.c", 27
	jsr     decsp5
	ldy     #$04
L0005:	lda     M0004,y
	sta     (c_sp),y
	dey
	bpl     L0005
	.dbg	line, "tests/decode_test.c", 30
	jsr     decsp5
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0059)
	ldx     #>(S0059)
	jsr     pushax
	lda     #<(S005A)
	ldx     #>(S005A)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/decode_test.c", 32
	ldx     #$00
	lda     #$00
	jsr     pushax
	lda     #$16
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$11
	jsr     _set_line
	.dbg	line, "tests/decode_test.c", 34
	jsr     _decode_number
	.dbg	line, "tests/decode_test.c", 35
	jsr     _decode_byte
	.dbg	line, "tests/decode_test.c", 36
	lda     c_sp
	ldx     c_sp+1
	jsr     _store_fp0
	.dbg	line, "tests/decode_test.c", 37
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S005B)
	ldx     #>(S005B)
	jsr     pushax
	lda     #<(S005C)
	ldx     #>(S005C)
	jsr     pushax
	ldx     #$00
	lda     #$25
	jsr     pushax
	lda     #<(S005D)
	ldx     #>(S005D)
	jsr     pushax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$12
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S005E)
	ldx     #>(S005E)
	jsr     pushax
	lda     #<(S005F)
	ldx     #>(S005F)
	jsr     pushax
	ldy     #$29
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$2D
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldy     #$15
	ldx     #$00
	lda     (c_sp),y
	jsr     toseqax
	jeq     L000C
	jmp     L000D
L000C:	lda     #<(S0060)
	ldx     #>(S0060)
	jsr     pushax
	ldx     #$00
	lda     #$25
	jsr     ___afailed
L000D:	lda     #<(S0061)
	ldx     #>(S0061)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0062)
	ldx     #>(S0062)
	jsr     pushax
	lda     #<(S0063)
	ldx     #>(S0063)
	jsr     pushax
	ldx     #$00
	lda     #$25
	jsr     pushax
	lda     #<(S0064)
	ldx     #>(S0064)
	jsr     pushax
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     pusheax
	lda     #<(S0065)
	ldx     #>(S0065)
	jsr     pushax
	lda     #<(S0066)
	ldx     #>(S0066)
	jsr     pushax
	ldy     #$28
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$2C
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$03
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$16
	jsr     ldeaxysp
	jsr     toseqeax
	jeq     L0011
	jmp     L0012
L0011:	lda     #<(S0067)
	ldx     #>(S0067)
	jsr     pushax
	ldx     #$00
	lda     #$25
	jsr     ___afailed
L0012:	lda     #<(S0068)
	ldx     #>(S0068)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 39
	jsr     _decode_number
	.dbg	line, "tests/decode_test.c", 40
	jsr     _decode_byte
	.dbg	line, "tests/decode_test.c", 41
	lda     c_sp
	ldx     c_sp+1
	jsr     _store_fp0
	.dbg	line, "tests/decode_test.c", 42
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0069)
	ldx     #>(S0069)
	jsr     pushax
	lda     #<(S006A)
	ldx     #>(S006A)
	jsr     pushax
	ldx     #$00
	lda     #$2A
	jsr     pushax
	lda     #<(S006B)
	ldx     #>(S006B)
	jsr     pushax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$12
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S006C)
	ldx     #>(S006C)
	jsr     pushax
	lda     #<(S006D)
	ldx     #>(S006D)
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$28
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldy     #$10
	ldx     #$00
	lda     (c_sp),y
	jsr     toseqax
	jeq     L0019
	jmp     L001A
L0019:	lda     #<(S006E)
	ldx     #>(S006E)
	jsr     pushax
	ldx     #$00
	lda     #$2A
	jsr     ___afailed
L001A:	lda     #<(S006F)
	ldx     #>(S006F)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0070)
	ldx     #>(S0070)
	jsr     pushax
	lda     #<(S0071)
	ldx     #>(S0071)
	jsr     pushax
	ldx     #$00
	lda     #$2A
	jsr     pushax
	lda     #<(S0072)
	ldx     #>(S0072)
	jsr     pushax
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     pusheax
	lda     #<(S0073)
	ldx     #>(S0073)
	jsr     pushax
	lda     #<(S0074)
	ldx     #>(S0074)
	jsr     pushax
	ldy     #$23
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$27
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$03
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     toseqeax
	jeq     L001E
	jmp     L001F
L001E:	lda     #<(S0075)
	ldx     #>(S0075)
	jsr     pushax
	ldx     #$00
	lda     #$2A
	jsr     ___afailed
L001F:	lda     #<(S0076)
	ldx     #>(S0076)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 44
	jsr     _decode_number
	.dbg	line, "tests/decode_test.c", 45
	jsr     _decode_byte
	.dbg	line, "tests/decode_test.c", 46
	lda     c_sp
	ldx     c_sp+1
	jsr     _store_fp0
	.dbg	line, "tests/decode_test.c", 47
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0077)
	ldx     #>(S0077)
	jsr     pushax
	lda     #<(S0078)
	ldx     #>(S0078)
	jsr     pushax
	ldx     #$00
	lda     #$2F
	jsr     pushax
	lda     #<(S0079)
	ldx     #>(S0079)
	jsr     pushax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$12
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S007A)
	ldx     #>(S007A)
	jsr     pushax
	lda     #<(S007B)
	ldx     #>(S007B)
	jsr     pushax
	ldy     #$1F
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$23
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldy     #$0B
	ldx     #$00
	lda     (c_sp),y
	jsr     toseqax
	jeq     L0026
	jmp     L0027
L0026:	lda     #<(S007C)
	ldx     #>(S007C)
	jsr     pushax
	ldx     #$00
	lda     #$2F
	jsr     ___afailed
L0027:	lda     #<(S007D)
	ldx     #>(S007D)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S007E)
	ldx     #>(S007E)
	jsr     pushax
	lda     #<(S007F)
	ldx     #>(S007F)
	jsr     pushax
	ldx     #$00
	lda     #$2F
	jsr     pushax
	lda     #<(S0080)
	ldx     #>(S0080)
	jsr     pushax
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     pusheax
	lda     #<(S0081)
	ldx     #>(S0081)
	jsr     pushax
	lda     #<(S0082)
	ldx     #>(S0082)
	jsr     pushax
	ldy     #$1E
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$22
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$03
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$0C
	jsr     ldeaxysp
	jsr     toseqeax
	jeq     L002B
	jmp     L002C
L002B:	lda     #<(S0083)
	ldx     #>(S0083)
	jsr     pushax
	ldx     #$00
	lda     #$2F
	jsr     ___afailed
L002C:	lda     #<(S0084)
	ldx     #>(S0084)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 48
	ldy     #$25
	jsr     addysp
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$31
	.byte	$30
	.byte	$30
	.byte	$2C
	.byte	$34
	.byte	$31
	.byte	$31
	.byte	$32
	.byte	$2C
	.byte	$33
	.byte	$2E
	.byte	$31
	.byte	$34
	.byte	$31
	.byte	$35
	.byte	$39
	.byte	$2C
M0002:
	.dword	$48000000
	.byte	$86
M0003:
	.dword	$00800000
	.byte	$8C
M0004:
	.dword	$490FCF81
	.byte	$81

.endproc

; ---------------------------------------------------------------
; void __near__ test_decode_string (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_decode_string: near

	.dbg	func, "test_decode_string", "00", static, "_test_decode_string"
	.dbg	sym, "line_data", "00", auto, -7

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 53
	jsr     decsp7
	ldy     #$06
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/decode_test.c", 55
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0085)
	ldx     #>(S0085)
	jsr     pushax
	lda     #<(S0086)
	ldx     #>(S0086)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/decode_test.c", 57
	jsr     _initialize_program
	.dbg	line, "tests/decode_test.c", 59
	ldx     #$00
	lda     #$00
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$07
	jsr     _set_line
	.dbg	line, "tests/decode_test.c", 61
	lda     #<(S0087)
	ldx     #>(S0087)
	jsr     pushax
	lda     #<(_line_buffer)
	ldx     #>(_line_buffer)
	jsr     pushax
	ldx     #$00
	lda     #$20
	jsr     _hexdump
	.dbg	line, "tests/decode_test.c", 62
	lda     #<(S0088)
	ldx     #>(S0088)
	jsr     pushax
	lda     _line_ptr
	ldx     _line_ptr+1
	jsr     pushax
	ldx     #$00
	lda     #$20
	jsr     _hexdump
	.dbg	line, "tests/decode_test.c", 64
	jsr     _decode_string
	.dbg	line, "tests/decode_test.c", 65
	lda     #<(S0089)
	ldx     #>(S0089)
	jsr     pushax
	lda     _string_ptr
	ldx     _string_ptr+1
	jsr     pushax
	ldx     #$00
	lda     #$20
	jsr     _hexdump
	.dbg	line, "tests/decode_test.c", 66
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S008A)
	ldx     #>(S008A)
	jsr     pushax
	lda     #<(S008B)
	ldx     #>(S008B)
	jsr     pushax
	ldx     #$00
	lda     #$42
	jsr     pushax
	lda     #<(S008C)
	ldx     #>(S008C)
	jsr     pushax
	lda     _string_ptr
	ldx     _string_ptr+1
	ldy     #$00
	jsr     ldauidx
	jsr     axulong
	jsr     pusheax
	lda     _string_ptr
	ldx     _string_ptr+1
	ldy     #$00
	jsr     ldauidx
	jsr     axulong
	jsr     pusheax
	lda     #<(S008D)
	ldx     #>(S008D)
	jsr     pushax
	lda     #<(S008E)
	ldx     #>(S008E)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$05
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$05
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	lda     _string_ptr
	ldx     _string_ptr+1
	ldy     #$00
	jsr     ldauidx
	cmp     #$05
	jsr     booleq
	jeq     L0006
	jmp     L0007
L0006:	lda     #<(S008F)
	ldx     #>(S008F)
	jsr     pushax
	ldx     #$00
	lda     #$42
	jsr     ___afailed
L0007:	lda     #<(S0090)
	ldx     #>(S0090)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 67
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0091)
	ldx     #>(S0091)
	jsr     pushax
	lda     #<(S0092)
	ldx     #>(S0092)
	jsr     pushax
	ldx     #$00
	lda     #$43
	jsr     pushax
	lda     #<(S0093)
	ldx     #>(S0093)
	jsr     pushax
	lda     _string_ptr
	ldx     _string_ptr+1
	jsr     incax1
	jsr     pushax
	lda     #<(S0094)
	ldx     #>(S0094)
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     _memcmp
	jsr     axlong
	jsr     pusheax
	lda     _string_ptr
	ldx     _string_ptr+1
	jsr     incax1
	jsr     pushax
	lda     #<(S0095)
	ldx     #>(S0095)
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     _memcmp
	jsr     axlong
	jsr     pusheax
	lda     #<(S0096)
	ldx     #>(S0096)
	jsr     pushax
	lda     #<(S0097)
	ldx     #>(S0097)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	lda     _string_ptr
	ldx     _string_ptr+1
	jsr     incax1
	jsr     pushax
	lda     #<(S0098)
	ldx     #>(S0098)
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     _memcmp
	cpx     #$00
	bne     L000B
	cmp     #$00
L000B:	jsr     booleq
	jeq     L000C
	jmp     L000D
L000C:	lda     #<(S0099)
	ldx     #>(S0099)
	jsr     pushax
	ldx     #$00
	lda     #$43
	jsr     ___afailed
L000D:	lda     #<(S009A)
	ldx     #>(S009A)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 68
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S009B)
	ldx     #>(S009B)
	jsr     pushax
	lda     #<(S009C)
	ldx     #>(S009C)
	jsr     pushax
	ldx     #$00
	lda     #$44
	jsr     pushax
	lda     #<(S009D)
	ldx     #>(S009D)
	jsr     pushax
	ldx     #$00
	lda     _line_pos
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _line_pos
	jsr     axulong
	jsr     pusheax
	lda     #<(S009E)
	ldx     #>(S009E)
	jsr     pushax
	lda     #<(S009F)
	ldx     #>(S009F)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$0A
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$0A
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _line_pos
	cmp     #$0A
	jsr     booleq
	jeq     L0011
	jmp     L0012
L0011:	lda     #<(S00A0)
	ldx     #>(S00A0)
	jsr     pushax
	ldx     #$00
	lda     #$44
	jsr     ___afailed
L0012:	lda     #<(S00A1)
	ldx     #>(S00A1)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 69
	jsr     incsp7
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$22
	.byte	$48
	.byte	$45
	.byte	$4C
	.byte	$4C
	.byte	$4F
	.byte	$22

.endproc

; ---------------------------------------------------------------
; void __near__ test_decode_name (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_decode_name: near

	.dbg	func, "test_decode_name", "00", static, "_test_decode_name"
	.dbg	sym, "line_data", "00", auto, -14

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 78
	ldy     #$0E
	jsr     subysp
	ldy     #$0D
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/decode_test.c", 80
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00A2)
	ldx     #>(S00A2)
	jsr     pushax
	lda     #<(S00A3)
	ldx     #>(S00A3)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/decode_test.c", 82
	ldx     #$00
	lda     #$00
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$0E
	jsr     _set_line
	.dbg	line, "tests/decode_test.c", 84
	jsr     _decode_name
	.dbg	line, "tests/decode_test.c", 85
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00A4)
	ldx     #>(S00A4)
	jsr     pushax
	lda     #<(S00A5)
	ldx     #>(S00A5)
	jsr     pushax
	ldx     #$00
	lda     #$55
	jsr     pushax
	lda     #<(S00A6)
	ldx     #>(S00A6)
	jsr     pushax
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	jsr     pushax
	lda     #<(S00A7)
	ldx     #>(S00A7)
	jsr     pushax
	lda     #<(S00A8)
	ldx     #>(S00A8)
	jsr     pushax
	lda     #<(_line_buffer+3)
	ldx     #>(_line_buffer+3)
	jsr     pushax
	ldy     #$12
	jsr     _fprintf
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	jsr     pushax
	lda     #<(_line_buffer+3)
	ldx     #>(_line_buffer+3)
	jsr     toseqax
	jeq     L0006
	jmp     L0007
L0006:	lda     #<(S00A9)
	ldx     #>(S00A9)
	jsr     pushax
	ldx     #$00
	lda     #$55
	jsr     ___afailed
L0007:	lda     #<(S00AA)
	ldx     #>(S00AA)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 86
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00AB)
	ldx     #>(S00AB)
	jsr     pushax
	lda     #<(S00AC)
	ldx     #>(S00AC)
	jsr     pushax
	ldx     #$00
	lda     #$56
	jsr     pushax
	lda     #<(S00AD)
	ldx     #>(S00AD)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_length
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_length
	jsr     axulong
	jsr     pusheax
	lda     #<(S00AE)
	ldx     #>(S00AE)
	jsr     pushax
	lda     #<(S00AF)
	ldx     #>(S00AF)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_length
	cmp     #$01
	jsr     booleq
	jeq     L000B
	jmp     L000C
L000B:	lda     #<(S00B0)
	ldx     #>(S00B0)
	jsr     pushax
	ldx     #$00
	lda     #$56
	jsr     ___afailed
L000C:	lda     #<(S00B1)
	ldx     #>(S00B1)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 87
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00B2)
	ldx     #>(S00B2)
	jsr     pushax
	lda     #<(S00B3)
	ldx     #>(S00B3)
	jsr     pushax
	ldx     #$00
	lda     #$57
	jsr     pushax
	lda     #<(S00B4)
	ldx     #>(S00B4)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_type
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_type
	jsr     axulong
	jsr     pusheax
	lda     #<(S00B5)
	ldx     #>(S00B5)
	jsr     pushax
	lda     #<(S00B6)
	ldx     #>(S00B6)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_type
	cmp     #$00
	jsr     booleq
	jeq     L0010
	jmp     L0011
L0010:	lda     #<(S00B7)
	ldx     #>(S00B7)
	jsr     pushax
	ldx     #$00
	lda     #$57
	jsr     ___afailed
L0011:	lda     #<(S00B8)
	ldx     #>(S00B8)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 88
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00B9)
	ldx     #>(S00B9)
	jsr     pushax
	lda     #<(S00BA)
	ldx     #>(S00BA)
	jsr     pushax
	ldx     #$00
	lda     #$58
	jsr     pushax
	lda     #<(S00BB)
	ldx     #>(S00BB)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_arity
	bpl     L0015
	dex
L0015:	jsr     axlong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_arity
	bpl     L0016
	dex
L0016:	jsr     axlong
	jsr     pusheax
	lda     #<(S00BC)
	ldx     #>(S00BC)
	jsr     pushax
	lda     #<(S00BD)
	ldx     #>(S00BD)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_arity
	bpl     L0017
	dex
L0017:	cmp     #$00
	jsr     booleq
	jeq     L0018
	jmp     L0019
L0018:	lda     #<(S00BE)
	ldx     #>(S00BE)
	jsr     pushax
	ldx     #$00
	lda     #$58
	jsr     ___afailed
L0019:	lda     #<(S00BF)
	ldx     #>(S00BF)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 90
	jsr     _decode_name
	.dbg	line, "tests/decode_test.c", 91
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00C0)
	ldx     #>(S00C0)
	jsr     pushax
	lda     #<(S00C1)
	ldx     #>(S00C1)
	jsr     pushax
	ldx     #$00
	lda     #$5B
	jsr     pushax
	lda     #<(S00C2)
	ldx     #>(S00C2)
	jsr     pushax
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	jsr     pushax
	lda     #<(S00C3)
	ldx     #>(S00C3)
	jsr     pushax
	lda     #<(S00C4)
	ldx     #>(S00C4)
	jsr     pushax
	lda     #<(_line_buffer+4)
	ldx     #>(_line_buffer+4)
	jsr     pushax
	ldy     #$12
	jsr     _fprintf
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	jsr     pushax
	lda     #<(_line_buffer+4)
	ldx     #>(_line_buffer+4)
	jsr     toseqax
	jeq     L001D
	jmp     L001E
L001D:	lda     #<(S00C5)
	ldx     #>(S00C5)
	jsr     pushax
	ldx     #$00
	lda     #$5B
	jsr     ___afailed
L001E:	lda     #<(S00C6)
	ldx     #>(S00C6)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 92
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00C7)
	ldx     #>(S00C7)
	jsr     pushax
	lda     #<(S00C8)
	ldx     #>(S00C8)
	jsr     pushax
	ldx     #$00
	lda     #$5C
	jsr     pushax
	lda     #<(S00C9)
	ldx     #>(S00C9)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_length
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_length
	jsr     axulong
	jsr     pusheax
	lda     #<(S00CA)
	ldx     #>(S00CA)
	jsr     pushax
	lda     #<(S00CB)
	ldx     #>(S00CB)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$06
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$06
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_length
	cmp     #$06
	jsr     booleq
	jeq     L0022
	jmp     L0023
L0022:	lda     #<(S00CC)
	ldx     #>(S00CC)
	jsr     pushax
	ldx     #$00
	lda     #$5C
	jsr     ___afailed
L0023:	lda     #<(S00CD)
	ldx     #>(S00CD)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 93
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00CE)
	ldx     #>(S00CE)
	jsr     pushax
	lda     #<(S00CF)
	ldx     #>(S00CF)
	jsr     pushax
	ldx     #$00
	lda     #$5D
	jsr     pushax
	lda     #<(S00D0)
	ldx     #>(S00D0)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_type
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_type
	jsr     axulong
	jsr     pusheax
	lda     #<(S00D1)
	ldx     #>(S00D1)
	jsr     pushax
	lda     #<(S00D2)
	ldx     #>(S00D2)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_type
	cmp     #$00
	jsr     booleq
	jeq     L0027
	jmp     L0028
L0027:	lda     #<(S00D3)
	ldx     #>(S00D3)
	jsr     pushax
	ldx     #$00
	lda     #$5D
	jsr     ___afailed
L0028:	lda     #<(S00D4)
	ldx     #>(S00D4)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 94
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00D5)
	ldx     #>(S00D5)
	jsr     pushax
	lda     #<(S00D6)
	ldx     #>(S00D6)
	jsr     pushax
	ldx     #$00
	lda     #$5E
	jsr     pushax
	lda     #<(S00D7)
	ldx     #>(S00D7)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_arity
	bpl     L002C
	dex
L002C:	jsr     axlong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_arity
	bpl     L002D
	dex
L002D:	jsr     axlong
	jsr     pusheax
	lda     #<(S00D8)
	ldx     #>(S00D8)
	jsr     pushax
	lda     #<(S00D9)
	ldx     #>(S00D9)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_arity
	bpl     L002E
	dex
L002E:	cmp     #$00
	jsr     booleq
	jeq     L002F
	jmp     L0030
L002F:	lda     #<(S00DA)
	ldx     #>(S00DA)
	jsr     pushax
	ldx     #$00
	lda     #$5E
	jsr     ___afailed
L0030:	lda     #<(S00DB)
	ldx     #>(S00DB)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 96
	jsr     _decode_name
	.dbg	line, "tests/decode_test.c", 97
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00DC)
	ldx     #>(S00DC)
	jsr     pushax
	lda     #<(S00DD)
	ldx     #>(S00DD)
	jsr     pushax
	ldx     #$00
	lda     #$61
	jsr     pushax
	lda     #<(S00DE)
	ldx     #>(S00DE)
	jsr     pushax
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	jsr     pushax
	lda     #<(S00DF)
	ldx     #>(S00DF)
	jsr     pushax
	lda     #<(S00E0)
	ldx     #>(S00E0)
	jsr     pushax
	lda     #<(_line_buffer+10)
	ldx     #>(_line_buffer+10)
	jsr     pushax
	ldy     #$12
	jsr     _fprintf
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	jsr     pushax
	lda     #<(_line_buffer+10)
	ldx     #>(_line_buffer+10)
	jsr     toseqax
	jeq     L0034
	jmp     L0035
L0034:	lda     #<(S00E1)
	ldx     #>(S00E1)
	jsr     pushax
	ldx     #$00
	lda     #$61
	jsr     ___afailed
L0035:	lda     #<(S00E2)
	ldx     #>(S00E2)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 98
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00E3)
	ldx     #>(S00E3)
	jsr     pushax
	lda     #<(S00E4)
	ldx     #>(S00E4)
	jsr     pushax
	ldx     #$00
	lda     #$62
	jsr     pushax
	lda     #<(S00E5)
	ldx     #>(S00E5)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_length
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_length
	jsr     axulong
	jsr     pusheax
	lda     #<(S00E6)
	ldx     #>(S00E6)
	jsr     pushax
	lda     #<(S00E7)
	ldx     #>(S00E7)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$02
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$02
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_length
	cmp     #$02
	jsr     booleq
	jeq     L0039
	jmp     L003A
L0039:	lda     #<(S00E8)
	ldx     #>(S00E8)
	jsr     pushax
	ldx     #$00
	lda     #$62
	jsr     ___afailed
L003A:	lda     #<(S00E9)
	ldx     #>(S00E9)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 99
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00EA)
	ldx     #>(S00EA)
	jsr     pushax
	lda     #<(S00EB)
	ldx     #>(S00EB)
	jsr     pushax
	ldx     #$00
	lda     #$63
	jsr     pushax
	lda     #<(S00EC)
	ldx     #>(S00EC)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_type
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_type
	jsr     axulong
	jsr     pusheax
	lda     #<(S00ED)
	ldx     #>(S00ED)
	jsr     pushax
	lda     #<(S00EE)
	ldx     #>(S00EE)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_type
	cmp     #$01
	jsr     booleq
	jeq     L003E
	jmp     L003F
L003E:	lda     #<(S00EF)
	ldx     #>(S00EF)
	jsr     pushax
	ldx     #$00
	lda     #$63
	jsr     ___afailed
L003F:	lda     #<(S00F0)
	ldx     #>(S00F0)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 100
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00F1)
	ldx     #>(S00F1)
	jsr     pushax
	lda     #<(S00F2)
	ldx     #>(S00F2)
	jsr     pushax
	ldx     #$00
	lda     #$64
	jsr     pushax
	lda     #<(S00F3)
	ldx     #>(S00F3)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_arity
	bpl     L0043
	dex
L0043:	jsr     axlong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_arity
	bpl     L0044
	dex
L0044:	jsr     axlong
	jsr     pusheax
	lda     #<(S00F4)
	ldx     #>(S00F4)
	jsr     pushax
	lda     #<(S00F5)
	ldx     #>(S00F5)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_arity
	bpl     L0045
	dex
L0045:	cmp     #$00
	jsr     booleq
	jeq     L0046
	jmp     L0047
L0046:	lda     #<(S00F6)
	ldx     #>(S00F6)
	jsr     pushax
	ldx     #$00
	lda     #$64
	jsr     ___afailed
L0047:	lda     #<(S00F7)
	ldx     #>(S00F7)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 102
	jsr     _decode_name
	.dbg	line, "tests/decode_test.c", 103
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00F8)
	ldx     #>(S00F8)
	jsr     pushax
	lda     #<(S00F9)
	ldx     #>(S00F9)
	jsr     pushax
	ldx     #$00
	lda     #$67
	jsr     pushax
	lda     #<(S00FA)
	ldx     #>(S00FA)
	jsr     pushax
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	jsr     pushax
	lda     #<(S00FB)
	ldx     #>(S00FB)
	jsr     pushax
	lda     #<(S00FC)
	ldx     #>(S00FC)
	jsr     pushax
	lda     #<(_line_buffer+12)
	ldx     #>(_line_buffer+12)
	jsr     pushax
	ldy     #$12
	jsr     _fprintf
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	jsr     pushax
	lda     #<(_line_buffer+12)
	ldx     #>(_line_buffer+12)
	jsr     toseqax
	jeq     L004B
	jmp     L004C
L004B:	lda     #<(S00FD)
	ldx     #>(S00FD)
	jsr     pushax
	ldx     #$00
	lda     #$67
	jsr     ___afailed
L004C:	lda     #<(S00FE)
	ldx     #>(S00FE)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 104
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00FF)
	ldx     #>(S00FF)
	jsr     pushax
	lda     #<(S0100)
	ldx     #>(S0100)
	jsr     pushax
	ldx     #$00
	lda     #$68
	jsr     pushax
	lda     #<(S0101)
	ldx     #>(S0101)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_length
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_length
	jsr     axulong
	jsr     pusheax
	lda     #<(S0102)
	ldx     #>(S0102)
	jsr     pushax
	lda     #<(S0103)
	ldx     #>(S0103)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_length
	cmp     #$01
	jsr     booleq
	jeq     L0050
	jmp     L0051
L0050:	lda     #<(S0104)
	ldx     #>(S0104)
	jsr     pushax
	ldx     #$00
	lda     #$68
	jsr     ___afailed
L0051:	lda     #<(S0105)
	ldx     #>(S0105)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 105
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0106)
	ldx     #>(S0106)
	jsr     pushax
	lda     #<(S0107)
	ldx     #>(S0107)
	jsr     pushax
	ldx     #$00
	lda     #$69
	jsr     pushax
	lda     #<(S0108)
	ldx     #>(S0108)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_type
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_type
	jsr     axulong
	jsr     pusheax
	lda     #<(S0109)
	ldx     #>(S0109)
	jsr     pushax
	lda     #<(S010A)
	ldx     #>(S010A)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_type
	cmp     #$00
	jsr     booleq
	jeq     L0055
	jmp     L0056
L0055:	lda     #<(S010B)
	ldx     #>(S010B)
	jsr     pushax
	ldx     #$00
	lda     #$69
	jsr     ___afailed
L0056:	lda     #<(S010C)
	ldx     #>(S010C)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 106
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S010D)
	ldx     #>(S010D)
	jsr     pushax
	lda     #<(S010E)
	ldx     #>(S010E)
	jsr     pushax
	ldx     #$00
	lda     #$6A
	jsr     pushax
	lda     #<(S010F)
	ldx     #>(S010F)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_arity
	bpl     L005A
	dex
L005A:	jsr     axlong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_arity
	bpl     L005B
	dex
L005B:	jsr     axlong
	jsr     pusheax
	lda     #<(S0110)
	ldx     #>(S0110)
	jsr     pushax
	lda     #<(S0111)
	ldx     #>(S0111)
	jsr     pushax
	lda     #$FF
	sta     sreg+1
	lda     #$FF
	sta     sreg
	lda     #$FF
	ldx     #$FF
	jsr     pusheax
	lda     #$FF
	sta     sreg+1
	lda     #$FF
	sta     sreg
	lda     #$FF
	ldx     #$FF
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_arity
	bpl     L005C
	dex
L005C:	cmp     #$FF
	jsr     booleq
	jeq     L005D
	jmp     L005E
L005D:	lda     #<(S0112)
	ldx     #>(S0112)
	jsr     pushax
	ldx     #$00
	lda     #$6A
	jsr     ___afailed
L005E:	lda     #<(S0113)
	ldx     #>(S0113)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 108
	jsr     _decode_name
	.dbg	line, "tests/decode_test.c", 109
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0114)
	ldx     #>(S0114)
	jsr     pushax
	lda     #<(S0115)
	ldx     #>(S0115)
	jsr     pushax
	ldx     #$00
	lda     #$6D
	jsr     pushax
	lda     #<(S0116)
	ldx     #>(S0116)
	jsr     pushax
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	jsr     pushax
	lda     #<(S0117)
	ldx     #>(S0117)
	jsr     pushax
	lda     #<(S0118)
	ldx     #>(S0118)
	jsr     pushax
	lda     #<(_line_buffer+14)
	ldx     #>(_line_buffer+14)
	jsr     pushax
	ldy     #$12
	jsr     _fprintf
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	jsr     pushax
	lda     #<(_line_buffer+14)
	ldx     #>(_line_buffer+14)
	jsr     toseqax
	jeq     L0062
	jmp     L0063
L0062:	lda     #<(S0119)
	ldx     #>(S0119)
	jsr     pushax
	ldx     #$00
	lda     #$6D
	jsr     ___afailed
L0063:	lda     #<(S011A)
	ldx     #>(S011A)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 110
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S011B)
	ldx     #>(S011B)
	jsr     pushax
	lda     #<(S011C)
	ldx     #>(S011C)
	jsr     pushax
	ldx     #$00
	lda     #$6E
	jsr     pushax
	lda     #<(S011D)
	ldx     #>(S011D)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_length
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_length
	jsr     axulong
	jsr     pusheax
	lda     #<(S011E)
	ldx     #>(S011E)
	jsr     pushax
	lda     #<(S011F)
	ldx     #>(S011F)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$02
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$02
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_length
	cmp     #$02
	jsr     booleq
	jeq     L0067
	jmp     L0068
L0067:	lda     #<(S0120)
	ldx     #>(S0120)
	jsr     pushax
	ldx     #$00
	lda     #$6E
	jsr     ___afailed
L0068:	lda     #<(S0121)
	ldx     #>(S0121)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 111
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0122)
	ldx     #>(S0122)
	jsr     pushax
	lda     #<(S0123)
	ldx     #>(S0123)
	jsr     pushax
	ldx     #$00
	lda     #$6F
	jsr     pushax
	lda     #<(S0124)
	ldx     #>(S0124)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_type
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_type
	jsr     axulong
	jsr     pusheax
	lda     #<(S0125)
	ldx     #>(S0125)
	jsr     pushax
	lda     #<(S0126)
	ldx     #>(S0126)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_type
	cmp     #$01
	jsr     booleq
	jeq     L006C
	jmp     L006D
L006C:	lda     #<(S0127)
	ldx     #>(S0127)
	jsr     pushax
	ldx     #$00
	lda     #$6F
	jsr     ___afailed
L006D:	lda     #<(S0128)
	ldx     #>(S0128)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 112
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0129)
	ldx     #>(S0129)
	jsr     pushax
	lda     #<(S012A)
	ldx     #>(S012A)
	jsr     pushax
	ldx     #$00
	lda     #$70
	jsr     pushax
	lda     #<(S012B)
	ldx     #>(S012B)
	jsr     pushax
	ldx     #$00
	lda     _decode_name_arity
	bpl     L0071
	dex
L0071:	jsr     axlong
	jsr     pusheax
	ldx     #$00
	lda     _decode_name_arity
	bpl     L0072
	dex
L0072:	jsr     axlong
	jsr     pusheax
	lda     #<(S012C)
	ldx     #>(S012C)
	jsr     pushax
	lda     #<(S012D)
	ldx     #>(S012D)
	jsr     pushax
	lda     #$FF
	sta     sreg+1
	lda     #$FF
	sta     sreg
	lda     #$FF
	ldx     #$FF
	jsr     pusheax
	lda     #$FF
	sta     sreg+1
	lda     #$FF
	sta     sreg
	lda     #$FF
	ldx     #$FF
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _decode_name_arity
	bpl     L0073
	dex
L0073:	cmp     #$FF
	jsr     booleq
	jeq     L0074
	jmp     L0075
L0074:	lda     #<(S012E)
	ldx     #>(S012E)
	jsr     pushax
	ldx     #$00
	lda     #$70
	jsr     ___afailed
L0075:	lda     #<(S012F)
	ldx     #>(S012F)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 113
	ldy     #$0E
	jsr     addysp
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$D8
	.byte	$54
	.byte	$48
	.byte	$49
	.byte	$4E
	.byte	$47
	.byte	$B3
	.byte	$41
	.byte	$A4
	.byte	$D8
	.byte	$28
	.byte	$41
	.byte	$A4
	.byte	$28

.endproc

; ---------------------------------------------------------------
; void __near__ xh_unary_operator (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_xh_unary_operator: near

	.dbg	func, "xh_unary_operator", "00", static, "_xh_unary_operator"
	.dbg	sym, "op", "00", auto, -1

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 120
	jsr     _decode_byte
	ldx     #$00
	and     #$FB
	ldx     #$00
	jsr     pusha
	.dbg	line, "tests/decode_test.c", 121
	inc     _unary_op_count
	bne     L0002
	inc     _unary_op_count+1
L0002:	lda     _unary_op_count
	ldx     _unary_op_count+1
	jmp     L0003
	.dbg	line, "tests/decode_test.c", 124
L0003:	cpx     #$00
	jne     L0004
	cmp     #$01
	jeq     L0005
	cmp     #$02
	jeq     L000B
	jmp     L0004
	jmp     L0004
	.dbg	line, "tests/decode_test.c", 122
L0005:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0130)
	ldx     #>(S0130)
	jsr     pushax
	lda     #<(S0131)
	ldx     #>(S0131)
	jsr     pushax
	ldx     #$00
	lda     #$7A
	jsr     pushax
	lda     #<(S0132)
	ldx     #>(S0132)
	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S0133)
	ldx     #>(S0133)
	jsr     pushax
	lda     #<(S0134)
	ldx     #>(S0134)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$00
	jsr     booleq
	jeq     L0009
	jmp     L000A
L0009:	lda     #<(S0135)
	ldx     #>(S0135)
	jsr     pushax
	ldx     #$00
	lda     #$7A
	jsr     ___afailed
L000A:	lda     #<(S0136)
	ldx     #>(S0136)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	jmp     L0004
	.dbg	line, "tests/decode_test.c", 123
L000B:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0137)
	ldx     #>(S0137)
	jsr     pushax
	lda     #<(S0138)
	ldx     #>(S0138)
	jsr     pushax
	ldx     #$00
	lda     #$7B
	jsr     pushax
	lda     #<(S0139)
	ldx     #>(S0139)
	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S013A)
	ldx     #>(S013A)
	jsr     pushax
	lda     #<(S013B)
	ldx     #>(S013B)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$01
	jsr     booleq
	jeq     L000F
	jmp     L0010
L000F:	lda     #<(S013C)
	ldx     #>(S013C)
	jsr     pushax
	ldx     #$00
	lda     #$7B
	jsr     ___afailed
L0010:	lda     #<(S013D)
	ldx     #>(S013D)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	jmp     L0004
	.dbg	line, "tests/decode_test.c", 125
L0004:	jsr     incsp1
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ xh_operator (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_xh_operator: near

	.dbg	func, "xh_operator", "00", static, "_xh_operator"
	.dbg	sym, "op", "00", auto, -1

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 130
	jsr     _decode_byte
	ldx     #$00
	and     #$EF
	ldx     #$00
	jsr     pusha
	.dbg	line, "tests/decode_test.c", 131
	inc     _op_count
	bne     L0002
	inc     _op_count+1
L0002:	lda     _op_count
	ldx     _op_count+1
	jmp     L0003
	.dbg	line, "tests/decode_test.c", 137
L0003:	cpx     #$00
	jne     L0004
	cmp     #$01
	jeq     L0005
	cmp     #$02
	jeq     L000B
	cmp     #$03
	jeq     L0011
	cmp     #$04
	jeq     L0017
	cmp     #$05
	jeq     L001D
	jmp     L0004
	jmp     L0004
	.dbg	line, "tests/decode_test.c", 132
L0005:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S013E)
	ldx     #>(S013E)
	jsr     pushax
	lda     #<(S013F)
	ldx     #>(S013F)
	jsr     pushax
	ldx     #$00
	lda     #$84
	jsr     pushax
	lda     #<(S0140)
	ldx     #>(S0140)
	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S0141)
	ldx     #>(S0141)
	jsr     pushax
	lda     #<(S0142)
	ldx     #>(S0142)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$00
	jsr     booleq
	jeq     L0009
	jmp     L000A
L0009:	lda     #<(S0143)
	ldx     #>(S0143)
	jsr     pushax
	ldx     #$00
	lda     #$84
	jsr     ___afailed
L000A:	lda     #<(S0144)
	ldx     #>(S0144)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	jmp     L0004
	.dbg	line, "tests/decode_test.c", 133
L000B:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0145)
	ldx     #>(S0145)
	jsr     pushax
	lda     #<(S0146)
	ldx     #>(S0146)
	jsr     pushax
	ldx     #$00
	lda     #$85
	jsr     pushax
	lda     #<(S0147)
	ldx     #>(S0147)
	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S0148)
	ldx     #>(S0148)
	jsr     pushax
	lda     #<(S0149)
	ldx     #>(S0149)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$03
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$03
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$03
	jsr     booleq
	jeq     L000F
	jmp     L0010
L000F:	lda     #<(S014A)
	ldx     #>(S014A)
	jsr     pushax
	ldx     #$00
	lda     #$85
	jsr     ___afailed
L0010:	lda     #<(S014B)
	ldx     #>(S014B)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	jmp     L0004
	.dbg	line, "tests/decode_test.c", 134
L0011:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S014C)
	ldx     #>(S014C)
	jsr     pushax
	lda     #<(S014D)
	ldx     #>(S014D)
	jsr     pushax
	ldx     #$00
	lda     #$86
	jsr     pushax
	lda     #<(S014E)
	ldx     #>(S014E)
	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S014F)
	ldx     #>(S014F)
	jsr     pushax
	lda     #<(S0150)
	ldx     #>(S0150)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$02
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$02
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$02
	jsr     booleq
	jeq     L0015
	jmp     L0016
L0015:	lda     #<(S0151)
	ldx     #>(S0151)
	jsr     pushax
	ldx     #$00
	lda     #$86
	jsr     ___afailed
L0016:	lda     #<(S0152)
	ldx     #>(S0152)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	jmp     L0004
	.dbg	line, "tests/decode_test.c", 135
L0017:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0153)
	ldx     #>(S0153)
	jsr     pushax
	lda     #<(S0154)
	ldx     #>(S0154)
	jsr     pushax
	ldx     #$00
	lda     #$87
	jsr     pushax
	lda     #<(S0155)
	ldx     #>(S0155)
	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S0156)
	ldx     #>(S0156)
	jsr     pushax
	lda     #<(S0157)
	ldx     #>(S0157)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$0D
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$0D
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$0D
	jsr     booleq
	jeq     L001B
	jmp     L001C
L001B:	lda     #<(S0158)
	ldx     #>(S0158)
	jsr     pushax
	ldx     #$00
	lda     #$87
	jsr     ___afailed
L001C:	lda     #<(S0159)
	ldx     #>(S0159)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	jmp     L0004
	.dbg	line, "tests/decode_test.c", 136
L001D:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S015A)
	ldx     #>(S015A)
	jsr     pushax
	lda     #<(S015B)
	ldx     #>(S015B)
	jsr     pushax
	ldx     #$00
	lda     #$88
	jsr     pushax
	lda     #<(S015C)
	ldx     #>(S015C)
	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S015D)
	ldx     #>(S015D)
	jsr     pushax
	lda     #<(S015E)
	ldx     #>(S015E)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$01
	jsr     booleq
	jeq     L0021
	jmp     L0022
L0021:	lda     #<(S015F)
	ldx     #>(S015F)
	jsr     pushax
	ldx     #$00
	lda     #$88
	jsr     ___afailed
L0022:	lda     #<(S0160)
	ldx     #>(S0160)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	jmp     L0004
	.dbg	line, "tests/decode_test.c", 138
L0004:	jsr     incsp1
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ xh_number (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_xh_number: near

	.dbg	func, "xh_number", "00", static, "_xh_number"
	.dbg	sym, "result_1", "00", auto, -5
	.dbg	sym, "result_2", "00", auto, -10
	.dbg	sym, "result", "00", auto, -15

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 143
	jsr     decsp5
	ldy     #$04
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/decode_test.c", 144
	jsr     decsp5
	ldy     #$04
L0003:	lda     M0002,y
	sta     (c_sp),y
	dey
	bpl     L0003
	.dbg	line, "tests/decode_test.c", 146
	jsr     decsp5
	jsr     _decode_number
	.dbg	line, "tests/decode_test.c", 147
	inc     _num_count
	bne     L0004
	inc     _num_count+1
L0004:	lda     _num_count
	ldx     _num_count+1
	jmp     L0005
	.dbg	line, "tests/decode_test.c", 150
L0005:	cpx     #$00
	jne     L0006
	cmp     #$01
	jeq     L0007
	cmp     #$02
	jeq     L0015
	jmp     L0006
	jmp     L0006
	.dbg	line, "tests/decode_test.c", 148
L0007:	lda     c_sp
	ldx     c_sp+1
	jsr     _store_fp0
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0161)
	ldx     #>(S0161)
	jsr     pushax
	lda     #<(S0162)
	ldx     #>(S0162)
	jsr     pushax
	ldx     #$00
	lda     #$94
	jsr     pushax
	lda     #<(S0163)
	ldx     #>(S0163)
	jsr     pushax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$12
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S0164)
	ldx     #>(S0164)
	jsr     pushax
	lda     #<(S0165)
	ldx     #>(S0165)
	jsr     pushax
	ldy     #$24
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$28
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldy     #$10
	ldx     #$00
	lda     (c_sp),y
	jsr     toseqax
	jeq     L000E
	jmp     L000F
L000E:	lda     #<(S0166)
	ldx     #>(S0166)
	jsr     pushax
	ldx     #$00
	lda     #$94
	jsr     ___afailed
L000F:	lda     #<(S0167)
	ldx     #>(S0167)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0168)
	ldx     #>(S0168)
	jsr     pushax
	lda     #<(S0169)
	ldx     #>(S0169)
	jsr     pushax
	ldx     #$00
	lda     #$94
	jsr     pushax
	lda     #<(S016A)
	ldx     #>(S016A)
	jsr     pushax
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     pusheax
	lda     #<(S016B)
	ldx     #>(S016B)
	jsr     pushax
	lda     #<(S016C)
	ldx     #>(S016C)
	jsr     pushax
	ldy     #$23
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$27
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$03
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     toseqeax
	jeq     L0013
	jmp     L0014
L0013:	lda     #<(S016D)
	ldx     #>(S016D)
	jsr     pushax
	ldx     #$00
	lda     #$94
	jsr     ___afailed
L0014:	lda     #<(S016E)
	ldx     #>(S016E)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	jmp     L0006
	.dbg	line, "tests/decode_test.c", 149
L0015:	lda     c_sp
	ldx     c_sp+1
	jsr     _store_fp0
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S016F)
	ldx     #>(S016F)
	jsr     pushax
	lda     #<(S0170)
	ldx     #>(S0170)
	jsr     pushax
	ldx     #$00
	lda     #$95
	jsr     pushax
	lda     #<(S0171)
	ldx     #>(S0171)
	jsr     pushax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$12
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S0172)
	ldx     #>(S0172)
	jsr     pushax
	lda     #<(S0173)
	ldx     #>(S0173)
	jsr     pushax
	ldy     #$1F
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$23
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldy     #$0B
	ldx     #$00
	lda     (c_sp),y
	jsr     toseqax
	jeq     L001C
	jmp     L001D
L001C:	lda     #<(S0174)
	ldx     #>(S0174)
	jsr     pushax
	ldx     #$00
	lda     #$95
	jsr     ___afailed
L001D:	lda     #<(S0175)
	ldx     #>(S0175)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0176)
	ldx     #>(S0176)
	jsr     pushax
	lda     #<(S0177)
	ldx     #>(S0177)
	jsr     pushax
	ldx     #$00
	lda     #$95
	jsr     pushax
	lda     #<(S0178)
	ldx     #>(S0178)
	jsr     pushax
	ldy     #$0D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$11
	jsr     ldeaxysp
	jsr     pusheax
	lda     #<(S0179)
	ldx     #>(S0179)
	jsr     pushax
	lda     #<(S017A)
	ldx     #>(S017A)
	jsr     pushax
	ldy     #$1E
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$22
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$03
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$0C
	jsr     ldeaxysp
	jsr     toseqeax
	jeq     L0021
	jmp     L0022
L0021:	lda     #<(S017B)
	ldx     #>(S017B)
	jsr     pushax
	ldx     #$00
	lda     #$95
	jsr     ___afailed
L0022:	lda     #<(S017C)
	ldx     #>(S017C)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	jmp     L0006
	.dbg	line, "tests/decode_test.c", 151
L0006:	ldy     #$0F
	jsr     addysp
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.dword	$00800000
	.byte	$8C
M0002:
	.dword	$40000000
	.byte	$81

.endproc

; ---------------------------------------------------------------
; void __near__ xh_string (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_xh_string: near

	.dbg	func, "xh_string", "00", static, "_xh_string"

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 154
	jsr     _decode_string
	.dbg	line, "tests/decode_test.c", 156
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ xh_variable (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_xh_variable: near

	.dbg	func, "xh_variable", "00", static, "_xh_variable"

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 161
	jsr     _decode_name
	.dbg	line, "tests/decode_test.c", 162
	inc     _var_count
	bne     L0002
	inc     _var_count+1
L0002:	lda     _var_count
	ldx     _var_count+1
	.dbg	line, "tests/decode_test.c", 163
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S017D)
	ldx     #>(S017D)
	jsr     pushax
	lda     #<(S017E)
	ldx     #>(S017E)
	jsr     pushax
	ldx     #$00
	lda     #$A3
	jsr     pushax
	lda     #<(S017F)
	ldx     #>(S017F)
	jsr     pushax
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	ldy     #$00
	jsr     ldauidx
	jsr     axulong
	jsr     pusheax
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	ldy     #$00
	jsr     ldauidx
	jsr     axulong
	jsr     pusheax
	lda     #<(S0180)
	ldx     #>(S0180)
	jsr     pushax
	lda     #<(S0181)
	ldx     #>(S0181)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$D8
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$D8
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	lda     _decode_name_ptr
	ldx     _decode_name_ptr+1
	ldy     #$00
	jsr     ldauidx
	cmp     #$D8
	jsr     booleq
	jeq     L0006
	jmp     L0007
L0006:	lda     #<(S0182)
	ldx     #>(S0182)
	jsr     pushax
	ldx     #$00
	lda     #$A3
	jsr     ___afailed
L0007:	lda     #<(S0183)
	ldx     #>(S0183)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 164
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ xh_function (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_xh_function: near

	.dbg	func, "xh_function", "00", static, "_xh_function"
	.dbg	sym, "function", "00", auto, -1

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 169
	jsr     _decode_byte
	ldx     #$00
	and     #$9F
	ldx     #$00
	jsr     pusha
	.dbg	line, "tests/decode_test.c", 170
	inc     _function_count
	bne     L0002
	inc     _function_count+1
L0002:	lda     _function_count
	ldx     _function_count+1
	.dbg	line, "tests/decode_test.c", 171
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0184)
	ldx     #>(S0184)
	jsr     pushax
	lda     #<(S0185)
	ldx     #>(S0185)
	jsr     pushax
	ldx     #$00
	lda     #$AB
	jsr     pushax
	lda     #<(S0186)
	ldx     #>(S0186)
	jsr     pushax
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	ldy     #$0E
	ldx     #$00
	lda     (c_sp),y
	jsr     axulong
	jsr     pusheax
	lda     #<(S0187)
	ldx     #>(S0187)
	jsr     pushax
	lda     #<(S0188)
	ldx     #>(S0188)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$00
	jsr     booleq
	jeq     L0006
	jmp     L0007
L0006:	lda     #<(S0189)
	ldx     #>(S0189)
	jsr     pushax
	ldx     #$00
	lda     #$AB
	jsr     ___afailed
L0007:	lda     #<(S018A)
	ldx     #>(S018A)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 172
	jsr     incsp1
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ xh_paren (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_xh_paren: near

	.dbg	func, "xh_paren", "00", static, "_xh_paren"

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 177
	inc     _paren_count
	bne     L0002
	inc     _paren_count+1
L0002:	lda     _paren_count
	ldx     _paren_count+1
	.dbg	line, "tests/decode_test.c", 178
	jsr     _decode_byte
	.dbg	line, "tests/decode_test.c", 179
	lda     #<(_decode_xh_vectors)
	ldx     #>(_decode_xh_vectors)
	jsr     _decode_expression
	.dbg	line, "tests/decode_test.c", 181
	jsr     _decode_byte
	.dbg	line, "tests/decode_test.c", 182
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ test_decode_expression (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_decode_expression: near

	.dbg	func, "test_decode_expression", "00", static, "_test_decode_expression"
	.dbg	sym, "line_data", "00", auto, -27

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 215
	ldy     #$1B
	jsr     subysp
	ldy     #$1A
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/decode_test.c", 217
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S018B)
	ldx     #>(S018B)
	jsr     pushax
	lda     #<(S018C)
	ldx     #>(S018C)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/decode_test.c", 219
	ldx     #$00
	lda     #$00
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$1B
	jsr     _set_line
	.dbg	line, "tests/decode_test.c", 221
	lda     #<(_decode_xh_vectors)
	ldx     #>(_decode_xh_vectors)
	jsr     _decode_expression
	.dbg	line, "tests/decode_test.c", 222
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S018D)
	ldx     #>(S018D)
	jsr     pushax
	lda     #<(S018E)
	ldx     #>(S018E)
	jsr     pushax
	ldx     #$00
	lda     #$DE
	jsr     pushax
	lda     #<(S018F)
	ldx     #>(S018F)
	jsr     pushax
	lda     _num_count
	ldx     _num_count+1
	jsr     axlong
	jsr     pusheax
	lda     _num_count
	ldx     _num_count+1
	jsr     axlong
	jsr     pusheax
	lda     #<(S0190)
	ldx     #>(S0190)
	jsr     pushax
	lda     #<(S0191)
	ldx     #>(S0191)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$02
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$02
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	lda     _num_count
	ldx     _num_count+1
	cpx     #$00
	bne     L0006
	cmp     #$02
L0006:	jsr     booleq
	jeq     L0007
	jmp     L0008
L0007:	lda     #<(S0192)
	ldx     #>(S0192)
	jsr     pushax
	ldx     #$00
	lda     #$DE
	jsr     ___afailed
L0008:	lda     #<(S0193)
	ldx     #>(S0193)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 223
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0194)
	ldx     #>(S0194)
	jsr     pushax
	lda     #<(S0195)
	ldx     #>(S0195)
	jsr     pushax
	ldx     #$00
	lda     #$DF
	jsr     pushax
	lda     #<(S0196)
	ldx     #>(S0196)
	jsr     pushax
	lda     _var_count
	ldx     _var_count+1
	jsr     axlong
	jsr     pusheax
	lda     _var_count
	ldx     _var_count+1
	jsr     axlong
	jsr     pusheax
	lda     #<(S0197)
	ldx     #>(S0197)
	jsr     pushax
	lda     #<(S0198)
	ldx     #>(S0198)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$03
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$03
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	lda     _var_count
	ldx     _var_count+1
	cpx     #$00
	bne     L000C
	cmp     #$03
L000C:	jsr     booleq
	jeq     L000D
	jmp     L000E
L000D:	lda     #<(S0199)
	ldx     #>(S0199)
	jsr     pushax
	ldx     #$00
	lda     #$DF
	jsr     ___afailed
L000E:	lda     #<(S019A)
	ldx     #>(S019A)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 224
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S019B)
	ldx     #>(S019B)
	jsr     pushax
	lda     #<(S019C)
	ldx     #>(S019C)
	jsr     pushax
	ldx     #$00
	lda     #$E0
	jsr     pushax
	lda     #<(S019D)
	ldx     #>(S019D)
	jsr     pushax
	lda     _op_count
	ldx     _op_count+1
	jsr     axlong
	jsr     pusheax
	lda     _op_count
	ldx     _op_count+1
	jsr     axlong
	jsr     pusheax
	lda     #<(S019E)
	ldx     #>(S019E)
	jsr     pushax
	lda     #<(S019F)
	ldx     #>(S019F)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$05
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$05
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	lda     _op_count
	ldx     _op_count+1
	cpx     #$00
	bne     L0012
	cmp     #$05
L0012:	jsr     booleq
	jeq     L0013
	jmp     L0014
L0013:	lda     #<(S01A0)
	ldx     #>(S01A0)
	jsr     pushax
	ldx     #$00
	lda     #$E0
	jsr     ___afailed
L0014:	lda     #<(S01A1)
	ldx     #>(S01A1)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 225
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S01A2)
	ldx     #>(S01A2)
	jsr     pushax
	lda     #<(S01A3)
	ldx     #>(S01A3)
	jsr     pushax
	ldx     #$00
	lda     #$E1
	jsr     pushax
	lda     #<(S01A4)
	ldx     #>(S01A4)
	jsr     pushax
	lda     _unary_op_count
	ldx     _unary_op_count+1
	jsr     axlong
	jsr     pusheax
	lda     _unary_op_count
	ldx     _unary_op_count+1
	jsr     axlong
	jsr     pusheax
	lda     #<(S01A5)
	ldx     #>(S01A5)
	jsr     pushax
	lda     #<(S01A6)
	ldx     #>(S01A6)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$02
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$02
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	lda     _unary_op_count
	ldx     _unary_op_count+1
	cpx     #$00
	bne     L0018
	cmp     #$02
L0018:	jsr     booleq
	jeq     L0019
	jmp     L001A
L0019:	lda     #<(S01A7)
	ldx     #>(S01A7)
	jsr     pushax
	ldx     #$00
	lda     #$E1
	jsr     ___afailed
L001A:	lda     #<(S01A8)
	ldx     #>(S01A8)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 226
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S01A9)
	ldx     #>(S01A9)
	jsr     pushax
	lda     #<(S01AA)
	ldx     #>(S01AA)
	jsr     pushax
	ldx     #$00
	lda     #$E2
	jsr     pushax
	lda     #<(S01AB)
	ldx     #>(S01AB)
	jsr     pushax
	lda     _function_count
	ldx     _function_count+1
	jsr     axlong
	jsr     pusheax
	lda     _function_count
	ldx     _function_count+1
	jsr     axlong
	jsr     pusheax
	lda     #<(S01AC)
	ldx     #>(S01AC)
	jsr     pushax
	lda     #<(S01AD)
	ldx     #>(S01AD)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	lda     _function_count
	ldx     _function_count+1
	cpx     #$00
	bne     L001E
	cmp     #$01
L001E:	jsr     booleq
	jeq     L001F
	jmp     L0020
L001F:	lda     #<(S01AE)
	ldx     #>(S01AE)
	jsr     pushax
	ldx     #$00
	lda     #$E2
	jsr     ___afailed
L0020:	lda     #<(S01AF)
	ldx     #>(S01AF)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 227
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S01B0)
	ldx     #>(S01B0)
	jsr     pushax
	lda     #<(S01B1)
	ldx     #>(S01B1)
	jsr     pushax
	ldx     #$00
	lda     #$E3
	jsr     pushax
	lda     #<(S01B2)
	ldx     #>(S01B2)
	jsr     pushax
	lda     _paren_count
	ldx     _paren_count+1
	jsr     axlong
	jsr     pusheax
	lda     _paren_count
	ldx     _paren_count+1
	jsr     axlong
	jsr     pusheax
	lda     #<(S01B3)
	ldx     #>(S01B3)
	jsr     pushax
	lda     #<(S01B4)
	ldx     #>(S01B4)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$01
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	lda     _paren_count
	ldx     _paren_count+1
	cpx     #$00
	bne     L0024
	cmp     #$01
L0024:	jsr     booleq
	jeq     L0025
	jmp     L0026
L0025:	lda     #<(S01B5)
	ldx     #>(S01B5)
	jsr     pushax
	ldx     #$00
	lda     #$E3
	jsr     ___afailed
L0026:	lda     #<(S01B6)
	ldx     #>(S01B6)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/decode_test.c", 228
	ldy     #$1B
	jsr     addysp
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$34
	.byte	$31
	.byte	$31
	.byte	$32
	.byte	$10
	.byte	$28
	.byte	$D8
	.byte	$13
	.byte	$33
	.byte	$29
	.byte	$12
	.byte	$04
	.byte	$D8
	.byte	$1D
	.byte	$05
	.byte	$D8
	.byte	$11
	.byte	$60
	.byte	$22
	.byte	$48
	.byte	$45
	.byte	$4C
	.byte	$4C
	.byte	$4F
	.byte	$22
	.byte	$29
	.byte	$00

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"

.segment	"CODE"

	.dbg	line, "tests/decode_test.c", 231
	jsr     _initialize_target
	.dbg	line, "tests/decode_test.c", 232
	jsr     _test_decode_byte
	.dbg	line, "tests/decode_test.c", 233
	jsr     _test_decode_number
	.dbg	line, "tests/decode_test.c", 234
	jsr     _test_decode_string
	.dbg	line, "tests/decode_test.c", 235
	jsr     _test_decode_name
	.dbg	line, "tests/decode_test.c", 236
	jsr     _test_decode_expression
	.dbg	line, "tests/decode_test.c", 237
	ldx     #$00
	lda     #$00
	jmp     L0001
	.dbg	line, "tests/decode_test.c", 238
L0001:	rts

	.dbg	line
.endproc

