;
; File generated by cc65 v 2.19 - Git 034f73a9e
;
	.fopt		compiler,"cc65 v 2.19 - Git 034f73a9e"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.dbg		file, "tests/parser_test.c", 12401, 1768062990
	.dbg		file, "tests/test.h", 8355, 1768147025
	.dbg		file, "/usr/local/share/cc65/include/assert.h", 3002, 1768078665
	.dbg		file, "/usr/local/share/cc65/include/stdio.h", 6999, 1768078665
	.dbg		file, "/usr/local/share/cc65/include/string.h", 5678, 1768078665
	.dbg		file, "/usr/local/share/cc65/include/ctype.h", 4485, 1768078665
	.dbg		file, "/usr/local/share/cc65/include/stddef.h", 3037, 1768078665
	.dbg		file, "tests/../constants.h", 3560, 1768148159
	.dbg		file, "tests/../zeropage.h", 5631, 1768148159
	.forceimport	__STARTUP__
	.dbg		sym, "stderr", "00", extern, "_stderr"
	.dbg		sym, "line_ptr", "00", extern, "_line_ptr"
	.dbg		sym, "buffer_pos", "00", extern, "_buffer_pos"
	.dbg		sym, "line_pos", "00", extern, "_line_pos"
	.dbg		sym, "err", "00", extern, "_err"
	.dbg		sym, "buffer", "00", extern, "_buffer"
	.dbg		sym, "line_buffer", "00", extern, "_line_buffer"
	.dbg		sym, "pvm_statement", "00", extern, "_pvm_statement"
	.dbg		sym, "pvm_expression", "00", extern, "_pvm_expression"
	.dbg		sym, "pvm_number", "00", extern, "_pvm_number"
	.dbg		sym, "pvm_string", "00", extern, "_pvm_string"
	.dbg		sym, "pvm_name", "00", extern, "_pvm_name"
	.import		___afailed
	.import		_stderr
	.import		_fprintf
	.import		_fputc
	.import		_fputs
	.import		_printf
	.import		_strcpy
	.import		_strlen
	.import		_memcmp
	.import		_memcpy
	.import		_isprint
	.importzp	_line_ptr
	.importzp	_buffer_pos
	.importzp	_line_pos
	.import		_err
	.import		_buffer
	.import		_line_buffer
	.import		_pvm_statement
	.import		_pvm_expression
	.import		_pvm_number
	.import		_pvm_string
	.import		_pvm_name
	.import		_decode_name
	.import		_parse_line
	.import		_parse_pvm
	.import		_initialize_target
	.export		_hexdump
	.export		_set_line
	.export		_parse_and_decode_name
	.export		_call_parse_pvm_expect_buffer_pos
	.export		_call_parse_pvm
	.export		_test_pvm_number
	.export		_test_pvm_string
	.export		_test_pvm_name
	.export		_test_pvm_expression
	.export		_test_pvm_statement
	.export		_call_parse_line
	.export		_test_parse_line
	.export		_main

.segment	"RODATA"

S005C:
	.byte	$28,$73,$69,$7A,$65,$5F,$74,$29,$20,$28,$26,$28,$28,$4C,$69,$6E
	.byte	$65,$2A,$29,$20,$30,$29,$2D,$3E,$64,$61,$74,$61,$29,$20,$2B,$20
	.byte	$65,$78,$70,$65,$63,$74,$5F,$6C,$69,$6E,$65,$5F,$64,$61,$74,$61
	.byte	$5F,$6C,$65,$6E,$67,$74,$68,$00
S00A7:
	.byte	$20,$20,$25,$73,$3A,$25,$75,$3A,$20,$61,$73,$73,$65,$72,$74,$20
	.byte	$25,$73,$20,$28,$25,$6C,$64,$2C,$20,$24,$25,$6C,$58,$29,$20,$25
	.byte	$73,$20,$25,$73,$20,$28,$25,$6C,$64,$2C,$20,$24,$25,$6C,$58,$29
	.byte	$3A,$20,$00
S0044	:=	S00A7+0
S00B4	:=	S00A7+0
S0058	:=	S00A7+0
S004B	:=	S00A7+0
S00AE:
	.byte	$20,$20,$25,$73,$3A,$25,$75,$3A,$20,$61,$73,$73,$65,$72,$74,$20
	.byte	$25,$75,$20,$62,$79,$74,$65,$28,$73,$29,$20,$6D,$65,$6D,$6F,$72
	.byte	$79,$20,$65,$71,$75,$61,$6C,$73,$3A,$0A,$00
S0052	:=	S00AE+0
S00B8:
	.byte	$65,$78,$70,$65,$63,$74,$5F,$6C,$69,$6E,$65,$2D,$3E,$6E,$65,$78
	.byte	$74,$5F,$6C,$69,$6E,$65,$5F,$6F,$66,$66,$73,$65,$74,$00
S00A5:
	.byte	$20,$20,$25,$73,$3A,$25,$64,$3A,$20,$70,$61,$72,$73,$65,$5F,$6C
	.byte	$69,$6E,$65,$28,$22,$25,$73,$22,$29,$0A,$00
S0042:
	.byte	$20,$20,$25,$73,$3A,$25,$64,$3A,$20,$70,$61,$72,$73,$65,$5F,$70
	.byte	$76,$6D,$28,$22,$25,$73,$22,$29,$0A,$00
S0075:
	.byte	$22,$49,$4E,$54,$45,$52,$4E,$41,$4C,$20,$22,$22,$51,$55,$4F,$54
	.byte	$45,$53,$22,$22,$22,$00
S0096:
	.byte	$46,$4F,$52,$20,$58,$3D,$31,$20,$54,$4F,$20,$32,$30,$20,$53,$54
	.byte	$45,$50,$20,$32,$00
S003C:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$25,$73,$20,$28,$24,$25,$30,$34
	.byte	$58,$29,$3A,$0A,$00
S00B2:
	.byte	$74,$65,$73,$74,$73,$2F,$70,$61,$72,$73,$65,$72,$5F,$74,$65,$73
	.byte	$74,$2E,$63,$00
S004C	:=	S00B2+0
S0049	:=	S00B2+0
S00AF	:=	S00B2+0
S00B5	:=	S00B2+0
S0059	:=	S00B2+0
S0045	:=	S00B2+0
S0053	:=	S00B2+0
S0099:
	.byte	$49,$46,$20,$58,$3D,$31,$20,$54,$48,$45,$4E,$20,$47,$4F,$54,$4F
	.byte	$20,$31,$30,$00
S009E:
	.byte	$4F,$4E,$20,$58,$20,$47,$4F,$53,$55,$42,$20,$31,$30,$2C,$32,$30
	.byte	$2C,$33,$30,$00
S0043	:=	S00B2+0
S00A6	:=	S00B2+0
S00A8	:=	S00B2+0
S0056	:=	S00B2+0
S003D:
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$25,$30,$34,$58,$20,$25,$30,$34
	.byte	$58,$20,$20,$00
S005D	:=	S00B2+0
S00B9	:=	S00B2+0
S00AC	:=	S00B2+0
S0050	:=	S00B2+0
S00A2:
	.byte	$44,$41,$54,$41,$20,$48,$45,$4C,$4C,$4F,$2C,$22,$58,$2C,$59,$22
	.byte	$2C,$35,$00
S007F:
	.byte	$74,$65,$73,$74,$5F,$70,$76,$6D,$5F,$65,$78,$70,$72,$65,$73,$73
	.byte	$69,$6F,$6E
S008E:
	.byte	$58,$20,$41,$4E,$44,$20,$28,$59,$20,$4F,$52,$20,$4E,$4F,$54,$20
	.byte	$5A,$29,$00
S0092:
	.byte	$74,$65,$73,$74,$5F,$70,$76,$6D,$5F,$73,$74,$61,$74,$65,$6D,$65
	.byte	$6E,$74
S0090:
	.byte	$4D,$49,$44,$24,$28,$22,$48,$45,$4C,$4C,$4F,$22,$2C,$32,$2C,$33
	.byte	$29,$00
S00BE:
	.byte	$4C,$45,$54,$20,$58,$3D,$31,$30,$30,$3A,$50,$52,$49,$4E,$54,$20
	.byte	$58,$00
S004F:
	.byte	$65,$78,$70,$65,$63,$74,$5F,$62,$75,$66,$66,$65,$72,$5F,$70,$6F
	.byte	$73,$00
S0055:
	.byte	$65,$78,$70,$65,$63,$74,$5F,$6C,$69,$6E,$65,$5F,$64,$61,$74,$61
	.byte	$00
S0054:
	.byte	$6C,$69,$6E,$65,$5F,$62,$75,$66,$66,$65,$72,$2E,$64,$61,$74,$61
	.byte	$00
S0060:
	.byte	$74,$65,$73,$74,$5F,$70,$76,$6D,$5F,$6E,$75,$6D,$62,$65,$72
S00BC:
	.byte	$74,$65,$73,$74,$5F,$70,$61,$72,$73,$65,$5F,$6C,$69,$6E,$65
S0071:
	.byte	$74,$65,$73,$74,$5F,$70,$76,$6D,$5F,$73,$74,$72,$69,$6E,$67
S009D:
	.byte	$4F,$4E,$20,$31,$20,$47,$4F,$53,$55,$42,$20,$31,$30,$00
S008F:
	.byte	$4C,$45,$4E,$28,$22,$48,$45,$4C,$4C,$4F,$22,$29,$00
S0095:
	.byte	$46,$4F,$52,$20,$58,$3D,$31,$20,$54,$4F,$20,$35,$00
S00A1:
	.byte	$4C,$49,$53,$54,$20,$31,$30,$30,$2C,$35,$30,$30,$00
S0077:
	.byte	$74,$65,$73,$74,$5F,$70,$76,$6D,$5F,$6E,$61,$6D,$65
S009C:
	.byte	$4F,$4E,$20,$31,$20,$47,$4F,$54,$4F,$20,$31,$30,$00
S00B0:
	.byte	$26,$6C,$69,$6E,$65,$5F,$62,$75,$66,$66,$65,$72,$00
S00A3:
	.byte	$50,$4F,$4B,$45,$20,$37,$31,$30,$2C,$20,$30,$00
S009B:
	.byte	$49,$4E,$50,$55,$54,$20,$41,$2C,$42,$2C,$43,$00
S00B1:
	.byte	$65,$78,$70,$65,$63,$74,$5F,$6C,$69,$6E,$65,$00
S00A9	:=	S004F+7
S00BF:
	.byte	$31,$30,$20,$50,$52,$49,$4E,$54,$20,$31,$00
S004D	:=	S004F+7
S0098:
	.byte	$4C,$45,$54,$20,$58,$3D,$31,$30,$30,$00
S0089:
	.byte	$22,$41,$22,$20,$26,$20,$22,$42,$22,$00
S00BD	:=	S0098+0
S0087:
	.byte	$20,$20,$31,$20,$20,$2B,$20,$20,$31,$00
S00AB:
	.byte	$73,$74,$72,$6C,$65,$6E,$28,$73,$29,$00
S0084:
	.byte	$53,$24,$28,$31,$2C,$32,$35,$29,$00
S00A4:
	.byte	$44,$49,$4D,$20,$41,$28,$35,$29,$00
S005A:
	.byte	$6C,$69,$6E,$65,$5F,$70,$6F,$73,$00
S00B6	:=	S005A+0
S00A0:
	.byte	$4C,$49,$53,$54,$20,$31,$30,$30,$00
S009A:
	.byte	$49,$4E,$50,$55,$54,$20,$41,$00
S0094	:=	S00BF+3
S0072:
	.byte	$22,$48,$45,$4C,$4C,$4F,$22,$00
S008D:
	.byte	$31,$2B,$28,$31,$2B,$31,$29,$00
S008A:
	.byte	$58,$20,$41,$4E,$44,$20,$59,$00
S0067:
	.byte	$33,$2E,$31,$34,$31,$35,$39,$00
S0066:
	.byte	$20,$20,$2D,$31,$30,$30,$00
S0097:
	.byte	$4E,$45,$58,$54,$20,$58,$00
S003E:
	.byte	$25,$30,$32,$58,$20,$00
S0088:
	.byte	$31,$2B,$31,$2F,$32,$00
S006D:
	.byte	$31,$30,$2E,$45,$35,$00
S008C:
	.byte	$4E,$4F,$54,$20,$31,$00
S007C:
	.byte	$58,$5F,$31,$30,$58,$00
S006E:
	.byte	$2E,$31,$30,$45,$35,$00
S006F:
	.byte	$31,$30,$45,$2D,$35,$00
S0086:
	.byte	$20,$20,$31,$2B,$31,$00
S0091:
	.byte	$25,$73,$3A,$0A,$00
S0083:
	.byte	$58,$28,$35,$29,$00
S0064:
	.byte	$20,$20,$39,$31,$00
S005F	:=	S0091+0
S008B:
	.byte	$31,$2B,$2D,$41,$00
S006C	:=	S006E+1
S007B:
	.byte	$58,$5F,$31,$30,$00
S0074:
	.byte	$20,$20,$22,$22,$00
S0065	:=	S0066+2
S007D:
	.byte	$58,$39,$41,$50,$00
S006A:
	.byte	$2E,$33,$35,$30,$00
S0069:
	.byte	$39,$38,$2E,$36,$00
S00BB	:=	S0091+0
S0070	:=	S0091+0
S009F:
	.byte	$4C,$49,$53,$54,$00
S007E	:=	S0091+0
S0076	:=	S0091+0
S006B:
	.byte	$2D,$2E,$35,$00
S0093:
	.byte	$45,$4E,$44,$00
S0085	:=	S0086+2
S0063:
	.byte	$39,$31,$58,$00
S00BA:
	.byte	$4F,$4B,$0A,$00
S003F:
	.byte	$20,$20,$20,$00
S00B3	:=	S00BA+0
S005E	:=	S00BA+0
S004A	:=	S00BA+0
S0051	:=	S00BA+0
S0057	:=	S00BA+0
S00AD	:=	S00BA+0
S007A:
	.byte	$58,$31,$30,$00
S0046:
	.byte	$65,$72,$72,$00
S0079:
	.byte	$58,$28,$00
S004E:
	.byte	$3D,$3D,$00
S00AA	:=	S004E+0
S0082:
	.byte	$53,$24,$00
S0062	:=	S0064+2
S0047	:=	S004E+0
S0073	:=	S0075+19
S00B7	:=	S004E+0
S005B	:=	S004E+0
S0068:
	.byte	$33,$2E,$00
S0048	:=	S0099+18
S0080	:=	S00BF+9
S0040	:=	S00A7+49
S0081	:=	S00BE+16
S0061	:=	S00BF+9
S0078	:=	S00BE+16
S0041	:=	S00AE+41

; ---------------------------------------------------------------
; void __near__ hexdump (const char *name, const char *data, unsigned int length)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_hexdump: near

	.dbg	func, "hexdump", "00", static, "_hexdump"
	.dbg	sym, "name", "00", auto, 4
	.dbg	sym, "data", "00", auto, 2
	.dbg	sym, "length", "00", auto, 0
	.dbg	sym, "i", "00", auto, -2
	.dbg	sym, "j", "00", auto, -4
	.dbg	sym, "p", "00", auto, -6

.segment	"CODE"

	.dbg	line, "tests/test.h", 225
	jsr     pushax
	.dbg	line, "tests/test.h", 228
	jsr     decsp6
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S003C)
	ldx     #>(S003C)
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     pushax
	ldy     #$08
	jsr     _fprintf
	.dbg	line, "tests/test.h", 229
	ldx     #$00
	lda     #$00
	ldy     #$04
	jsr     staxysp
L0002:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     tosultax
	jne     L0005
	jmp     L0003
	.dbg	line, "tests/test.h", 230
L0005:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S003D)
	ldx     #>(S003D)
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0F
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	ldy     #$08
	jsr     _fprintf
	.dbg	line, "tests/test.h", 231
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$00
	jsr     staxysp
	.dbg	line, "tests/test.h", 232
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
L0006:	ldy     #$03
	jsr     ldaxysp
	cpx     #$00
	bne     L000A
	cmp     #$10
L000A:	jsr     boolult
	jne     L0009
	jmp     L0007
	.dbg	line, "tests/test.h", 233
L0009:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     tosultax
	jeq     L000B
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S003E)
	ldx     #>(S003E)
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/test.h", 234
	jmp     L0008
L000B:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S003F)
	ldx     #>(S003F)
	jsr     pushax
	ldy     #$04
	jsr     _fprintf
	.dbg	line, "tests/test.h", 232
L0008:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0006
	.dbg	line, "tests/test.h", 236
L0007:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0040)
	ldx     #>(S0040)
	jsr     pushax
	ldy     #$04
	jsr     _fprintf
	.dbg	line, "tests/test.h", 237
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosaddax
	ldy     #$00
	jsr     staxysp
	.dbg	line, "tests/test.h", 238
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
L000D:	ldy     #$03
	jsr     ldaxysp
	cpx     #$00
	bne     L0011
	cmp     #$10
L0011:	jsr     boolult
	jne     L0010
	jmp     L000E
	.dbg	line, "tests/test.h", 239
L0010:	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     tosaddax
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     tosultax
	jeq     L0012
	ldy     #$01
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     _isprint
	stx     tmp1
	ora     tmp1
	jeq     L0013
	ldy     #$01
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jmp     L0014
L0013:	ldx     #$00
	lda     #$2E
L0014:	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputc
	.dbg	line, "tests/test.h", 240
	jmp     L000F
L0012:	ldx     #$00
	lda     #$20
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputc
	.dbg	line, "tests/test.h", 238
L000F:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L000D
	.dbg	line, "tests/test.h", 242
L000E:	lda     #<(S0041)
	ldx     #>(S0041)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	.dbg	line, "tests/test.h", 229
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	jsr     addeqysp
	jmp     L0002
	.dbg	line, "tests/test.h", 244
L0003:	ldy     #$0C
	jsr     addysp
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ set_line (int line, const char *data, unsigned int length)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_line: near

	.dbg	func, "set_line", "00", static, "_set_line"
	.dbg	sym, "line", "00", auto, 4
	.dbg	sym, "data", "00", auto, 2
	.dbg	sym, "length", "00", auto, 0

.segment	"CODE"

	.dbg	line, "tests/test.h", 246
	jsr     pushax
	.dbg	line, "tests/test.h", 247
	ldy     #$05
	jsr     ldaxysp
	sta     _line_buffer+1
	stx     _line_buffer+1+1
	.dbg	line, "tests/test.h", 248
	ldy     #$01
	jsr     ldaxysp
	jsr     incax3
	ldx     #$00
	sta     _line_buffer
	.dbg	line, "tests/test.h", 249
	lda     #<(_line_buffer+3)
	ldx     #>(_line_buffer+3)
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     _memcpy
	.dbg	line, "tests/test.h", 250
	lda     #<(_line_buffer)
	ldx     #>(_line_buffer)
	sta     _line_ptr
	stx     _line_ptr+1
	.dbg	line, "tests/test.h", 251
	ldx     #$00
	lda     #$03
	sta     _line_pos
	.dbg	line, "tests/test.h", 252
	jsr     incsp6
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ parse_and_decode_name (const char *name)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_parse_and_decode_name: near

	.dbg	func, "parse_and_decode_name", "00", static, "_parse_and_decode_name"
	.dbg	sym, "name", "00", auto, 0
	.dbg	sym, "length", "00", auto, -2

.segment	"CODE"

	.dbg	line, "tests/test.h", 254
	jsr     pushax
	.dbg	line, "tests/test.h", 257
	ldy     #$01
	jsr     ldaxysp
	jsr     _strlen
	jsr     pushax
	.dbg	line, "tests/test.h", 258
	lda     #<(_line_buffer+3)
	ldx     #>(_line_buffer+3)
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     _memcpy
	.dbg	line, "tests/test.h", 259
	ldy     #$01
	jsr     ldaxysp
	jsr     decax1
	clc
	adc     #<(_line_buffer+3)
	tay
	txa
	adc     #>(_line_buffer+3)
	tax
	tya
	jsr     pushax
	ldy     #$00
	jsr     ldauidx
	ora     #$80
	ldy     #$00
	jsr     staspidx
	.dbg	line, "tests/test.h", 260
	lda     #<(_line_buffer)
	ldx     #>(_line_buffer)
	sta     _line_ptr
	stx     _line_ptr+1
	.dbg	line, "tests/test.h", 261
	ldx     #$00
	lda     #$03
	sta     _line_pos
	.dbg	line, "tests/test.h", 262
	jsr     _decode_name
	.dbg	line, "tests/test.h", 263
	jsr     incsp4
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ call_parse_pvm_expect_buffer_pos (const char *s, const char *start, const char *expect_line_data, unsigned int expect_line_data_length, unsigned int expect_buffer_pos, int line)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_call_parse_pvm_expect_buffer_pos: near

	.dbg	func, "call_parse_pvm_expect_buffer_pos", "00", static, "_call_parse_pvm_expect_buffer_pos"
	.dbg	sym, "s", "00", auto, 10
	.dbg	sym, "start", "00", auto, 8
	.dbg	sym, "expect_line_data", "00", auto, 6
	.dbg	sym, "expect_line_data_length", "00", auto, 4
	.dbg	sym, "expect_buffer_pos", "00", auto, 2
	.dbg	sym, "line", "00", auto, 0

.segment	"CODE"

	.dbg	line, "tests/parser_test.c", 4
	jsr     pushax
	.dbg	line, "tests/parser_test.c", 5
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0042)
	ldx     #>(S0042)
	jsr     pushax
	lda     #<(S0043)
	ldx     #>(S0043)
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$13
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0A
	jsr     _fprintf
	.dbg	line, "tests/parser_test.c", 6
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     _strcpy
	.dbg	line, "tests/parser_test.c", 7
	ldx     #$00
	lda     #$00
	sta     _buffer_pos
	.dbg	line, "tests/parser_test.c", 8
	ldx     #$00
	lda     #$03
	sta     _line_pos
	.dbg	line, "tests/parser_test.c", 9
	ldy     #$09
	jsr     ldaxysp
	jsr     _parse_pvm
	.dbg	line, "tests/parser_test.c", 10
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0044)
	ldx     #>(S0044)
	jsr     pushax
	lda     #<(S0045)
	ldx     #>(S0045)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     pushax
	lda     #<(S0046)
	ldx     #>(S0046)
	jsr     pushax
	ldx     #$00
	lda     _err
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _err
	jsr     axulong
	jsr     pusheax
	lda     #<(S0047)
	ldx     #>(S0047)
	jsr     pushax
	lda     #<(S0048)
	ldx     #>(S0048)
	jsr     pushax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	lda     #$00
	sta     sreg+1
	lda     #$00
	sta     sreg
	lda     #$00
	ldx     #$00
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _err
	cmp     #$00
	jsr     booleq
	jeq     L0005
	jmp     L0006
L0005:	lda     #<(S0049)
	ldx     #>(S0049)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     ___afailed
L0006:	lda     #<(S004A)
	ldx     #>(S004A)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/parser_test.c", 11
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S004B)
	ldx     #>(S004B)
	jsr     pushax
	lda     #<(S004C)
	ldx     #>(S004C)
	jsr     pushax
	ldx     #$00
	lda     #$0B
	jsr     pushax
	lda     #<(S004D)
	ldx     #>(S004D)
	jsr     pushax
	ldx     #$00
	lda     _buffer_pos
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _buffer_pos
	jsr     axulong
	jsr     pusheax
	lda     #<(S004E)
	ldx     #>(S004E)
	jsr     pushax
	lda     #<(S004F)
	ldx     #>(S004F)
	jsr     pushax
	ldy     #$19
	jsr     ldaxysp
	jsr     axulong
	jsr     pusheax
	ldy     #$1D
	jsr     ldaxysp
	jsr     axulong
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _buffer_pos
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     toseqax
	jeq     L000A
	jmp     L000B
L000A:	lda     #<(S0050)
	ldx     #>(S0050)
	jsr     pushax
	ldx     #$00
	lda     #$0B
	jsr     ___afailed
L000B:	lda     #<(S0051)
	ldx     #>(S0051)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/parser_test.c", 12
	ldy     #$07
	lda     (c_sp),y
	dey
	ora     (c_sp),y
	jeq     L000F
	.dbg	line, "tests/parser_test.c", 13
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0052)
	ldx     #>(S0052)
	jsr     pushax
	lda     #<(S0053)
	ldx     #>(S0053)
	jsr     pushax
	ldx     #$00
	lda     #$0D
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0A
	jsr     _fprintf
	lda     #<(S0054)
	ldx     #>(S0054)
	jsr     pushax
	lda     #<(_line_buffer+3)
	ldx     #>(_line_buffer+3)
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     _hexdump
	lda     #<(S0055)
	ldx     #>(S0055)
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     _hexdump
	lda     #<(_line_buffer+3)
	ldx     #>(_line_buffer+3)
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     _memcmp
	cpx     #$00
	bne     L0010
	cmp     #$00
L0010:	jsr     booleq
	jeq     L0011
	jmp     L0012
L0011:	lda     #<(S0056)
	ldx     #>(S0056)
	jsr     pushax
	ldx     #$00
	lda     #$0D
	jsr     ___afailed
L0012:	lda     #<(S0057)
	ldx     #>(S0057)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/parser_test.c", 15
L000F:	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0058)
	ldx     #>(S0058)
	jsr     pushax
	lda     #<(S0059)
	ldx     #>(S0059)
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     pushax
	lda     #<(S005A)
	ldx     #>(S005A)
	jsr     pushax
	ldx     #$00
	lda     _line_pos
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _line_pos
	jsr     axulong
	jsr     pusheax
	lda     #<(S005B)
	ldx     #>(S005B)
	jsr     pushax
	lda     #<(S005C)
	ldx     #>(S005C)
	jsr     pushax
	ldy     #$1B
	jsr     ldaxysp
	jsr     incax3
	jsr     axulong
	jsr     pusheax
	ldy     #$1F
	jsr     ldaxysp
	jsr     incax3
	jsr     axulong
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _line_pos
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     incax3
	jsr     toseqax
	jeq     L0016
	jmp     L0017
L0016:	lda     #<(S005D)
	ldx     #>(S005D)
	jsr     pushax
	ldx     #$00
	lda     #$0F
	jsr     ___afailed
L0017:	lda     #<(S005E)
	ldx     #>(S005E)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/parser_test.c", 16
	ldy     #$0C
	jsr     addysp
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ call_parse_pvm (const char *s, const char *start, const char *expect_line_data, unsigned int expect_line_data_length, int line)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_call_parse_pvm: near

	.dbg	func, "call_parse_pvm", "00", static, "_call_parse_pvm"
	.dbg	sym, "s", "00", auto, 8
	.dbg	sym, "start", "00", auto, 6
	.dbg	sym, "expect_line_data", "00", auto, 4
	.dbg	sym, "expect_line_data_length", "00", auto, 2
	.dbg	sym, "line", "00", auto, 0

.segment	"CODE"

	.dbg	line, "tests/parser_test.c", 19
	jsr     pushax
	.dbg	line, "tests/parser_test.c", 20
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$09
	jsr     ldaxysp
	jsr     pushax
	ldy     #$11
	jsr     ldaxysp
	jsr     _strlen
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	jsr     _call_parse_pvm_expect_buffer_pos
	.dbg	line, "tests/parser_test.c", 21
	ldy     #$0A
	jsr     addysp
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ test_pvm_number (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_pvm_number: near

	.dbg	func, "test_pvm_number", "00", static, "_test_pvm_number"
	.dbg	sym, "line_data_1", "00", auto, -1
	.dbg	sym, "line_data_2", "00", auto, -3
	.dbg	sym, "line_data_3", "00", auto, -7
	.dbg	sym, "line_data_4", "00", auto, -14
	.dbg	sym, "line_data_5", "00", auto, -16
	.dbg	sym, "line_data_6", "00", auto, -20
	.dbg	sym, "line_data_7", "00", auto, -24
	.dbg	sym, "line_data_8", "00", auto, -27
	.dbg	sym, "line_data_9", "00", auto, -31
	.dbg	sym, "line_data_10", "00", auto, -36
	.dbg	sym, "line_data_11", "00", auto, -41
	.dbg	sym, "line_data_12", "00", auto, -46

.segment	"CODE"

	.dbg	line, "tests/parser_test.c", 25
	jsr     decsp1
	ldy     #$00
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/parser_test.c", 26
	jsr     decsp2
	ldy     #$01
L0003:	lda     M0002,y
	sta     (c_sp),y
	dey
	bpl     L0003
	.dbg	line, "tests/parser_test.c", 27
	jsr     decsp4
	ldy     #$03
L0004:	lda     M0003,y
	sta     (c_sp),y
	dey
	bpl     L0004
	.dbg	line, "tests/parser_test.c", 28
	jsr     decsp7
	ldy     #$06
L0005:	lda     M0004,y
	sta     (c_sp),y
	dey
	bpl     L0005
	.dbg	line, "tests/parser_test.c", 29
	jsr     decsp2
	ldy     #$01
L0006:	lda     M0005,y
	sta     (c_sp),y
	dey
	bpl     L0006
	.dbg	line, "tests/parser_test.c", 30
	jsr     decsp4
	ldy     #$03
L0007:	lda     M0006,y
	sta     (c_sp),y
	dey
	bpl     L0007
	.dbg	line, "tests/parser_test.c", 31
	jsr     decsp4
	ldy     #$03
L0008:	lda     M0007,y
	sta     (c_sp),y
	dey
	bpl     L0008
	.dbg	line, "tests/parser_test.c", 32
	jsr     decsp3
	ldy     #$02
L0009:	lda     M0008,y
	sta     (c_sp),y
	dey
	bpl     L0009
	.dbg	line, "tests/parser_test.c", 33
	jsr     decsp4
	ldy     #$03
L000A:	lda     M0009,y
	sta     (c_sp),y
	dey
	bpl     L000A
	.dbg	line, "tests/parser_test.c", 34
	jsr     decsp5
	ldy     #$04
L000B:	lda     M000A,y
	sta     (c_sp),y
	dey
	bpl     L000B
	.dbg	line, "tests/parser_test.c", 35
	jsr     decsp5
	ldy     #$04
L000C:	lda     M000B,y
	sta     (c_sp),y
	dey
	bpl     L000C
	.dbg	line, "tests/parser_test.c", 36
	jsr     decsp5
	ldy     #$04
L000D:	lda     M000C,y
	sta     (c_sp),y
	dey
	bpl     L000D
	.dbg	line, "tests/parser_test.c", 38
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S005F)
	ldx     #>(S005F)
	jsr     pushax
	lda     #<(S0060)
	ldx     #>(S0060)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/parser_test.c", 40
	lda     #<(S0061)
	ldx     #>(S0061)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$31
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	ldx     #$00
	lda     #$28
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 41
	lda     #<(S0062)
	ldx     #>(S0062)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$29
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 42
	lda     #<(S0063)
	ldx     #>(S0063)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$2A
	jsr     _call_parse_pvm_expect_buffer_pos
	.dbg	line, "tests/parser_test.c", 43
	lda     #<(S0064)
	ldx     #>(S0064)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$2F
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$2B
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 44
	lda     #<(S0065)
	ldx     #>(S0065)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$2B
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$2C
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 45
	lda     #<(S0066)
	ldx     #>(S0066)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$2B
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$2D
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 46
	lda     #<(S0067)
	ldx     #>(S0067)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$24
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$07
	jsr     pushax
	ldx     #$00
	lda     #$2E
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 47
	lda     #<(S0068)
	ldx     #>(S0068)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$22
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$2F
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 48
	lda     #<(S0069)
	ldx     #>(S0069)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$1E
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$30
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 49
	lda     #<(S006A)
	ldx     #>(S006A)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$1A
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$31
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 50
	lda     #<(S006B)
	ldx     #>(S006B)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$17
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$03
	jsr     pushax
	ldx     #$00
	lda     #$32
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 51
	lda     #<(S006C)
	ldx     #>(S006C)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$13
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$33
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 52
	lda     #<(S006D)
	ldx     #>(S006D)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$0E
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldx     #$00
	lda     #$34
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 53
	lda     #<(S006E)
	ldx     #>(S006E)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$09
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldx     #$00
	lda     #$35
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 54
	lda     #<(S006F)
	ldx     #>(S006F)
	jsr     pushax
	lda     #<(_pvm_number)
	ldx     #>(_pvm_number)
	jsr     pushax
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldx     #$00
	lda     #$36
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 55
	ldy     #$2E
	jsr     addysp
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$31
M0002:
	.byte	$39
	.byte	$31
M0003:
	.byte	$2D
	.byte	$31
	.byte	$30
	.byte	$30
M0004:
	.byte	$33
	.byte	$2E
	.byte	$31
	.byte	$34
	.byte	$31
	.byte	$35
	.byte	$39
M0005:
	.byte	$33
	.byte	$2E
M0006:
	.byte	$39
	.byte	$38
	.byte	$2E
	.byte	$36
M0007:
	.byte	$2E
	.byte	$33
	.byte	$35
	.byte	$30
M0008:
	.byte	$2D
	.byte	$2E
	.byte	$35
M0009:
	.byte	$31
	.byte	$30
	.byte	$45
	.byte	$35
M000A:
	.byte	$31
	.byte	$30
	.byte	$2E
	.byte	$45
	.byte	$35
M000B:
	.byte	$2E
	.byte	$31
	.byte	$30
	.byte	$45
	.byte	$35
M000C:
	.byte	$31
	.byte	$30
	.byte	$45
	.byte	$2D
	.byte	$35

.endproc

; ---------------------------------------------------------------
; void __near__ test_pvm_string (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_pvm_string: near

	.dbg	func, "test_pvm_string", "00", static, "_test_pvm_string"
	.dbg	sym, "line_data_1", "00", auto, -7
	.dbg	sym, "line_data_2", "00", auto, -9
	.dbg	sym, "line_data_3", "00", auto, -30

.segment	"CODE"

	.dbg	line, "tests/parser_test.c", 59
	jsr     decsp7
	ldy     #$06
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/parser_test.c", 60
	jsr     decsp2
	ldy     #$01
L0003:	lda     M0002,y
	sta     (c_sp),y
	dey
	bpl     L0003
	.dbg	line, "tests/parser_test.c", 61
	ldy     #$15
	jsr     subysp
	ldy     #$14
L0004:	lda     M0003,y
	sta     (c_sp),y
	dey
	bpl     L0004
	.dbg	line, "tests/parser_test.c", 63
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0070)
	ldx     #>(S0070)
	jsr     pushax
	lda     #<(S0071)
	ldx     #>(S0071)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/parser_test.c", 65
	lda     #<(S0072)
	ldx     #>(S0072)
	jsr     pushax
	lda     #<(_pvm_string)
	ldx     #>(_pvm_string)
	jsr     pushax
	lda     #$1B
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$07
	jsr     pushax
	ldx     #$00
	lda     #$41
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 66
	lda     #<(S0073)
	ldx     #>(S0073)
	jsr     pushax
	lda     #<(_pvm_string)
	ldx     #>(_pvm_string)
	jsr     pushax
	lda     #$19
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$42
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 67
	lda     #<(S0074)
	ldx     #>(S0074)
	jsr     pushax
	lda     #<(_pvm_string)
	ldx     #>(_pvm_string)
	jsr     pushax
	lda     #$19
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$43
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 68
	lda     #<(S0075)
	ldx     #>(S0075)
	jsr     pushax
	lda     #<(_pvm_string)
	ldx     #>(_pvm_string)
	jsr     pushax
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$15
	jsr     pushax
	ldx     #$00
	lda     #$44
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 69
	ldy     #$1E
	jsr     addysp
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$22
	.byte	$48
	.byte	$45
	.byte	$4C
	.byte	$4C
	.byte	$4F
	.byte	$22
M0002:
	.byte	$22
	.byte	$22
M0003:
	.byte	$22
	.byte	$49
	.byte	$4E
	.byte	$54
	.byte	$45
	.byte	$52
	.byte	$4E
	.byte	$41
	.byte	$4C
	.byte	$20
	.byte	$22
	.byte	$22
	.byte	$51
	.byte	$55
	.byte	$4F
	.byte	$54
	.byte	$45
	.byte	$53
	.byte	$22
	.byte	$22
	.byte	$22

.endproc

; ---------------------------------------------------------------
; void __near__ test_pvm_name (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_pvm_name: near

	.dbg	func, "test_pvm_name", "00", static, "_test_pvm_name"
	.dbg	sym, "line_data_1", "00", auto, -1
	.dbg	sym, "line_data_2", "00", auto, -4
	.dbg	sym, "line_data_3", "00", auto, -8
	.dbg	sym, "line_data_4", "00", auto, -13
	.dbg	sym, "line_data_5", "00", auto, -17

.segment	"CODE"

	.dbg	line, "tests/parser_test.c", 73
	jsr     decsp1
	ldy     #$00
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/parser_test.c", 74
	jsr     decsp3
	ldy     #$02
L0003:	lda     M0002,y
	sta     (c_sp),y
	dey
	bpl     L0003
	.dbg	line, "tests/parser_test.c", 75
	jsr     decsp4
	ldy     #$03
L0004:	lda     M0003,y
	sta     (c_sp),y
	dey
	bpl     L0004
	.dbg	line, "tests/parser_test.c", 76
	jsr     decsp5
	ldy     #$04
L0005:	lda     M0004,y
	sta     (c_sp),y
	dey
	bpl     L0005
	.dbg	line, "tests/parser_test.c", 77
	jsr     decsp4
	ldy     #$03
L0006:	lda     M0005,y
	sta     (c_sp),y
	dey
	bpl     L0006
	.dbg	line, "tests/parser_test.c", 79
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0076)
	ldx     #>(S0076)
	jsr     pushax
	lda     #<(S0077)
	ldx     #>(S0077)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/parser_test.c", 81
	lda     #<(S0078)
	ldx     #>(S0078)
	jsr     pushax
	lda     #<(_pvm_name)
	ldx     #>(_pvm_name)
	jsr     pushax
	lda     #$14
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	ldx     #$00
	lda     #$51
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 82
	lda     #<(S0079)
	ldx     #>(S0079)
	jsr     pushax
	lda     #<(_pvm_name)
	ldx     #>(_pvm_name)
	jsr     pushax
	lda     #$14
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	ldx     #$00
	lda     #$52
	jsr     _call_parse_pvm_expect_buffer_pos
	.dbg	line, "tests/parser_test.c", 83
	lda     #<(S007A)
	ldx     #>(S007A)
	jsr     pushax
	lda     #<(_pvm_name)
	ldx     #>(_pvm_name)
	jsr     pushax
	lda     #$11
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$03
	jsr     pushax
	ldx     #$00
	lda     #$53
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 84
	lda     #<(S007B)
	ldx     #>(S007B)
	jsr     pushax
	lda     #<(_pvm_name)
	ldx     #>(_pvm_name)
	jsr     pushax
	lda     #$0D
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$54
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 85
	lda     #<(S007C)
	ldx     #>(S007C)
	jsr     pushax
	lda     #<(_pvm_name)
	ldx     #>(_pvm_name)
	jsr     pushax
	lda     #$08
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldx     #$00
	lda     #$55
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 86
	lda     #<(S007D)
	ldx     #>(S007D)
	jsr     pushax
	lda     #<(_pvm_name)
	ldx     #>(_pvm_name)
	jsr     pushax
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$56
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 87
	ldy     #$11
	jsr     addysp
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$58
M0002:
	.byte	$58
	.byte	$31
	.byte	$30
M0003:
	.byte	$58
	.byte	$5F
	.byte	$31
	.byte	$30
M0004:
	.byte	$58
	.byte	$5F
	.byte	$31
	.byte	$30
	.byte	$58
M0005:
	.byte	$58
	.byte	$39
	.byte	$41
	.byte	$50

.endproc

; ---------------------------------------------------------------
; void __near__ test_pvm_expression (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_pvm_expression: near

	.dbg	func, "test_pvm_expression", "00", static, "_test_pvm_expression"
	.dbg	sym, "constant_line_data_1", "00", auto, -1
	.dbg	sym, "variable_line_data_1", "00", auto, -2
	.dbg	sym, "variable_line_data_2", "00", auto, -4
	.dbg	sym, "variable_line_data_3", "00", auto, -8
	.dbg	sym, "variable_line_data_4", "00", auto, -16
	.dbg	sym, "operator_line_data_1", "00", auto, -19
	.dbg	sym, "operator_line_data_2", "00", auto, -24
	.dbg	sym, "operator_line_data_3", "00", auto, -31
	.dbg	sym, "operator_line_data_4", "00", auto, -34
	.dbg	sym, "unary_operator_line_data_1", "00", auto, -38
	.dbg	sym, "unary_operator_line_data_2", "00", auto, -40
	.dbg	sym, "parens_line_data_1", "00", auto, -47
	.dbg	sym, "parens_line_data_2", "00", auto, -55
	.dbg	sym, "function_line_data_1", "00", auto, -65
	.dbg	sym, "function_line_data_2", "00", auto, -79

.segment	"CODE"

	.dbg	line, "tests/parser_test.c", 91
	jsr     decsp1
	ldy     #$00
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/parser_test.c", 93
	jsr     decsp1
	ldy     #$00
L0003:	lda     M0002,y
	sta     (c_sp),y
	dey
	bpl     L0003
	.dbg	line, "tests/parser_test.c", 94
	jsr     decsp2
	ldy     #$01
L0004:	lda     M0003,y
	sta     (c_sp),y
	dey
	bpl     L0004
	.dbg	line, "tests/parser_test.c", 95
	jsr     decsp4
	ldy     #$03
L0005:	lda     M0004,y
	sta     (c_sp),y
	dey
	bpl     L0005
	.dbg	line, "tests/parser_test.c", 96
	jsr     decsp8
	ldy     #$07
L0006:	lda     M0005,y
	sta     (c_sp),y
	dey
	bpl     L0006
	.dbg	line, "tests/parser_test.c", 98
	jsr     decsp3
	ldy     #$02
L0007:	lda     M0006,y
	sta     (c_sp),y
	dey
	bpl     L0007
	.dbg	line, "tests/parser_test.c", 99
	jsr     decsp5
	ldy     #$04
L0008:	lda     M0007,y
	sta     (c_sp),y
	dey
	bpl     L0008
	.dbg	line, "tests/parser_test.c", 100
	jsr     decsp7
	ldy     #$06
L0009:	lda     M0008,y
	sta     (c_sp),y
	dey
	bpl     L0009
	.dbg	line, "tests/parser_test.c", 101
	jsr     decsp3
	ldy     #$02
L000A:	lda     M0009,y
	sta     (c_sp),y
	dey
	bpl     L000A
	.dbg	line, "tests/parser_test.c", 103
	jsr     decsp4
	ldy     #$03
L000B:	lda     M000A,y
	sta     (c_sp),y
	dey
	bpl     L000B
	.dbg	line, "tests/parser_test.c", 104
	jsr     decsp2
	ldy     #$01
L000C:	lda     M000B,y
	sta     (c_sp),y
	dey
	bpl     L000C
	.dbg	line, "tests/parser_test.c", 106
	jsr     decsp7
	ldy     #$06
L000D:	lda     M000C,y
	sta     (c_sp),y
	dey
	bpl     L000D
	.dbg	line, "tests/parser_test.c", 107
	jsr     decsp8
	ldy     #$07
L000E:	lda     M000D,y
	sta     (c_sp),y
	dey
	bpl     L000E
	.dbg	line, "tests/parser_test.c", 109
	ldy     #$0A
	jsr     subysp
	ldy     #$09
L000F:	lda     M000E,y
	sta     (c_sp),y
	dey
	bpl     L000F
	.dbg	line, "tests/parser_test.c", 110
	ldy     #$0E
	jsr     subysp
	ldy     #$0D
L0010:	lda     M000F,y
	sta     (c_sp),y
	dey
	bpl     L0010
	.dbg	line, "tests/parser_test.c", 112
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S007E)
	ldx     #>(S007E)
	jsr     pushax
	lda     #<(S007F)
	ldx     #>(S007F)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/parser_test.c", 115
	lda     #<(S0080)
	ldx     #>(S0080)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$52
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	ldx     #$00
	lda     #$73
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 118
	lda     #<(S0081)
	ldx     #>(S0081)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$51
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	ldx     #$00
	lda     #$76
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 119
	lda     #<(S0082)
	ldx     #>(S0082)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$4F
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$77
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 120
	lda     #<(S0083)
	ldx     #>(S0083)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$4B
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$78
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 121
	lda     #<(S0084)
	ldx     #>(S0084)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$43
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     pushax
	ldx     #$00
	lda     #$79
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 124
	lda     #<(S0085)
	ldx     #>(S0085)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$40
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$03
	jsr     pushax
	ldx     #$00
	lda     #$7C
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 125
	lda     #<(S0086)
	ldx     #>(S0086)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$40
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$03
	jsr     pushax
	ldx     #$00
	lda     #$7D
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 126
	lda     #<(S0087)
	ldx     #>(S0087)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$40
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$03
	jsr     pushax
	ldx     #$00
	lda     #$7E
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 127
	lda     #<(S0088)
	ldx     #>(S0088)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$3B
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldx     #$00
	lda     #$7F
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 128
	lda     #<(S0089)
	ldx     #>(S0089)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$34
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$07
	jsr     pushax
	ldx     #$00
	lda     #$80
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 129
	lda     #<(S008A)
	ldx     #>(S008A)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$31
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$03
	jsr     pushax
	ldx     #$00
	lda     #$81
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 132
	lda     #<(S008B)
	ldx     #>(S008B)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$2D
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$84
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 133
	lda     #<(S008C)
	ldx     #>(S008C)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$2B
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$85
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 136
	lda     #<(S008D)
	ldx     #>(S008D)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$24
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$07
	jsr     pushax
	ldx     #$00
	lda     #$88
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 137
	lda     #<(S008E)
	ldx     #>(S008E)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$1C
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     pushax
	ldx     #$00
	lda     #$89
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 140
	lda     #<(S008F)
	ldx     #>(S008F)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$12
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     pushax
	ldx     #$00
	lda     #$8C
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 141
	lda     #<(S0090)
	ldx     #>(S0090)
	jsr     pushax
	lda     #<(_pvm_expression)
	ldx     #>(_pvm_expression)
	jsr     pushax
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$0E
	jsr     pushax
	ldx     #$00
	lda     #$8D
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 142
	ldy     #$4F
	jsr     addysp
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$31
M0002:
	.byte	$D8
M0003:
	.byte	$53
	.byte	$A4
M0004:
	.byte	$D8
	.byte	$28
	.byte	$35
	.byte	$29
M0005:
	.byte	$53
	.byte	$A4
	.byte	$28
	.byte	$31
	.byte	$2C
	.byte	$32
	.byte	$35
	.byte	$29
M0006:
	.byte	$31
	.byte	$10
	.byte	$31
M0007:
	.byte	$31
	.byte	$10
	.byte	$31
	.byte	$13
	.byte	$32
M0008:
	.byte	$22
	.byte	$41
	.byte	$22
	.byte	$15
	.byte	$22
	.byte	$42
	.byte	$22
M0009:
	.byte	$D8
	.byte	$1C
	.byte	$D9
M000A:
	.byte	$31
	.byte	$10
	.byte	$04
	.byte	$C1
M000B:
	.byte	$05
	.byte	$31
M000C:
	.byte	$31
	.byte	$10
	.byte	$28
	.byte	$31
	.byte	$10
	.byte	$31
	.byte	$29
M000D:
	.byte	$D8
	.byte	$1C
	.byte	$28
	.byte	$D9
	.byte	$1D
	.byte	$05
	.byte	$DA
	.byte	$29
M000E:
	.byte	$60
	.byte	$28
	.byte	$22
	.byte	$48
	.byte	$45
	.byte	$4C
	.byte	$4C
	.byte	$4F
	.byte	$22
	.byte	$29
M000F:
	.byte	$66
	.byte	$28
	.byte	$22
	.byte	$48
	.byte	$45
	.byte	$4C
	.byte	$4C
	.byte	$4F
	.byte	$22
	.byte	$2C
	.byte	$32
	.byte	$2C
	.byte	$33
	.byte	$29

.endproc

; ---------------------------------------------------------------
; void __near__ test_pvm_statement (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_pvm_statement: near

	.dbg	func, "test_pvm_statement", "00", static, "_test_pvm_statement"
	.dbg	sym, "simple_line_data_1", "00", auto, -1
	.dbg	sym, "print_line_data_1", "00", auto, -3
	.dbg	sym, "for_line_data_1", "00", auto, -9
	.dbg	sym, "for_line_data_2", "00", auto, -18
	.dbg	sym, "next_line_data_1", "00", auto, -20
	.dbg	sym, "let_line_data_1", "00", auto, -26
	.dbg	sym, "if_line_data_1", "00", auto, -34
	.dbg	sym, "input_line_data_1", "00", auto, -36
	.dbg	sym, "input_line_data_2", "00", auto, -42
	.dbg	sym, "on_line_data_1", "00", auto, -47
	.dbg	sym, "on_line_data_2", "00", auto, -52
	.dbg	sym, "on_line_data_3", "00", auto, -63
	.dbg	sym, "list_line_data_1", "00", auto, -64
	.dbg	sym, "list_line_data_2", "00", auto, -68
	.dbg	sym, "list_line_data_3", "00", auto, -76
	.dbg	sym, "data_line_data_1", "00", auto, -90
	.dbg	sym, "poke_line_data_1", "00", auto, -96
	.dbg	sym, "dim_line_data_1", "00", auto, -101

.segment	"CODE"

	.dbg	line, "tests/parser_test.c", 146
	jsr     decsp1
	ldy     #$00
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/parser_test.c", 147
	jsr     decsp2
	ldy     #$01
L0003:	lda     M0002,y
	sta     (c_sp),y
	dey
	bpl     L0003
	.dbg	line, "tests/parser_test.c", 148
	jsr     decsp6
	ldy     #$05
L0004:	lda     M0003,y
	sta     (c_sp),y
	dey
	bpl     L0004
	.dbg	line, "tests/parser_test.c", 149
	ldy     #$09
	jsr     subysp
	ldy     #$08
L0005:	lda     M0004,y
	sta     (c_sp),y
	dey
	bpl     L0005
	.dbg	line, "tests/parser_test.c", 150
	jsr     decsp2
	ldy     #$01
L0006:	lda     M0005,y
	sta     (c_sp),y
	dey
	bpl     L0006
	.dbg	line, "tests/parser_test.c", 151
	jsr     decsp6
	ldy     #$05
L0007:	lda     M0006,y
	sta     (c_sp),y
	dey
	bpl     L0007
	.dbg	line, "tests/parser_test.c", 152
	jsr     decsp8
	ldy     #$07
L0008:	lda     M0007,y
	sta     (c_sp),y
	dey
	bpl     L0008
	.dbg	line, "tests/parser_test.c", 153
	jsr     decsp2
	ldy     #$01
L0009:	lda     M0008,y
	sta     (c_sp),y
	dey
	bpl     L0009
	.dbg	line, "tests/parser_test.c", 154
	jsr     decsp6
	ldy     #$05
L000A:	lda     M0009,y
	sta     (c_sp),y
	dey
	bpl     L000A
	.dbg	line, "tests/parser_test.c", 155
	jsr     decsp5
	ldy     #$04
L000B:	lda     M000A,y
	sta     (c_sp),y
	dey
	bpl     L000B
	.dbg	line, "tests/parser_test.c", 156
	jsr     decsp5
	ldy     #$04
L000C:	lda     M000B,y
	sta     (c_sp),y
	dey
	bpl     L000C
	.dbg	line, "tests/parser_test.c", 157
	ldy     #$0B
	jsr     subysp
	ldy     #$0A
L000D:	lda     M000C,y
	sta     (c_sp),y
	dey
	bpl     L000D
	.dbg	line, "tests/parser_test.c", 158
	jsr     decsp1
	ldy     #$00
L000E:	lda     M000D,y
	sta     (c_sp),y
	dey
	bpl     L000E
	.dbg	line, "tests/parser_test.c", 159
	jsr     decsp4
	ldy     #$03
L000F:	lda     M000E,y
	sta     (c_sp),y
	dey
	bpl     L000F
	.dbg	line, "tests/parser_test.c", 160
	jsr     decsp8
	ldy     #$07
L0010:	lda     M000F,y
	sta     (c_sp),y
	dey
	bpl     L0010
	.dbg	line, "tests/parser_test.c", 161
	ldy     #$0E
	jsr     subysp
	ldy     #$0D
L0011:	lda     M0010,y
	sta     (c_sp),y
	dey
	bpl     L0011
	.dbg	line, "tests/parser_test.c", 162
	jsr     decsp6
	ldy     #$05
L0012:	lda     M0011,y
	sta     (c_sp),y
	dey
	bpl     L0012
	.dbg	line, "tests/parser_test.c", 163
	jsr     decsp5
	ldy     #$04
L0013:	lda     M0012,y
	sta     (c_sp),y
	dey
	bpl     L0013
	.dbg	line, "tests/parser_test.c", 165
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0091)
	ldx     #>(S0091)
	jsr     pushax
	lda     #<(S0092)
	ldx     #>(S0092)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/parser_test.c", 168
	lda     #<(S0093)
	ldx     #>(S0093)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$68
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	ldx     #$00
	lda     #$A8
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 171
	lda     #<(S0094)
	ldx     #>(S0094)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$66
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$AB
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 174
	lda     #<(S0095)
	ldx     #>(S0095)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$60
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$06
	jsr     pushax
	ldx     #$00
	lda     #$AE
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 175
	lda     #<(S0096)
	ldx     #>(S0096)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$57
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$09
	jsr     pushax
	ldx     #$00
	lda     #$AF
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 178
	lda     #<(S0097)
	ldx     #>(S0097)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$55
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$B2
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 181
	lda     #<(S0098)
	ldx     #>(S0098)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$4F
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$06
	jsr     pushax
	ldx     #$00
	lda     #$B5
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 184
	lda     #<(S0099)
	ldx     #>(S0099)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$47
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     pushax
	ldx     #$00
	lda     #$B8
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 187
	lda     #<(S009A)
	ldx     #>(S009A)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$45
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$02
	jsr     pushax
	ldx     #$00
	lda     #$BB
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 188
	lda     #<(S009B)
	ldx     #>(S009B)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$3F
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$06
	jsr     pushax
	ldx     #$00
	lda     #$BC
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 191
	lda     #<(S009C)
	ldx     #>(S009C)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$3A
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldx     #$00
	lda     #$BF
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 192
	lda     #<(S009D)
	ldx     #>(S009D)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$35
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldx     #$00
	lda     #$C0
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 193
	lda     #<(S009E)
	ldx     #>(S009E)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$2A
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$0B
	jsr     pushax
	ldx     #$00
	lda     #$C1
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 196
	lda     #<(S009F)
	ldx     #>(S009F)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$29
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$01
	jsr     pushax
	ldx     #$00
	lda     #$C4
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 197
	lda     #<(S00A0)
	ldx     #>(S00A0)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$25
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$04
	jsr     pushax
	ldx     #$00
	lda     #$C5
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 198
	lda     #<(S00A1)
	ldx     #>(S00A1)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$1D
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$08
	jsr     pushax
	ldx     #$00
	lda     #$C6
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 201
	lda     #<(S00A2)
	ldx     #>(S00A2)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$0F
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$0E
	jsr     pushax
	ldx     #$00
	lda     #$C9
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 204
	lda     #<(S00A3)
	ldx     #>(S00A3)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$09
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$06
	jsr     pushax
	ldx     #$00
	lda     #$CC
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 207
	lda     #<(S00A4)
	ldx     #>(S00A4)
	jsr     pushax
	lda     #<(_pvm_statement)
	ldx     #>(_pvm_statement)
	jsr     pushax
	lda     #$04
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$05
	jsr     pushax
	ldx     #$00
	lda     #$CF
	jsr     _call_parse_pvm
	.dbg	line, "tests/parser_test.c", 208
	ldy     #$65
	jsr     addysp
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$00
M0002:
	.byte	$02
	.byte	$31
M0003:
	.byte	$0B
	.byte	$D8
	.byte	$3D
	.byte	$31
	.byte	$0C
	.byte	$35
M0004:
	.byte	$0B
	.byte	$D8
	.byte	$3D
	.byte	$31
	.byte	$0C
	.byte	$32
	.byte	$30
	.byte	$0D
	.byte	$32
M0005:
	.byte	$0C
	.byte	$D8
M0006:
	.byte	$03
	.byte	$D8
	.byte	$3D
	.byte	$31
	.byte	$30
	.byte	$30
M0007:
	.byte	$0F
	.byte	$D8
	.byte	$16
	.byte	$31
	.byte	$09
	.byte	$06
	.byte	$31
	.byte	$30
M0008:
	.byte	$04
	.byte	$C1
M0009:
	.byte	$04
	.byte	$C1
	.byte	$2C
	.byte	$C2
	.byte	$2C
	.byte	$C3
M000A:
	.byte	$0A
	.byte	$31
	.byte	$0A
	.byte	$31
	.byte	$30
M000B:
	.byte	$0A
	.byte	$31
	.byte	$0B
	.byte	$31
	.byte	$30
M000C:
	.byte	$0A
	.byte	$D8
	.byte	$0B
	.byte	$31
	.byte	$30
	.byte	$2C
	.byte	$32
	.byte	$30
	.byte	$2C
	.byte	$33
	.byte	$30
M000D:
	.byte	$05
M000E:
	.byte	$05
	.byte	$31
	.byte	$30
	.byte	$30
M000F:
	.byte	$05
	.byte	$31
	.byte	$30
	.byte	$30
	.byte	$2C
	.byte	$35
	.byte	$30
	.byte	$30
M0010:
	.byte	$14
	.byte	$48
	.byte	$45
	.byte	$4C
	.byte	$4C
	.byte	$4F
	.byte	$2C
	.byte	$22
	.byte	$58
	.byte	$2C
	.byte	$59
	.byte	$22
	.byte	$2C
	.byte	$35
M0011:
	.byte	$17
	.byte	$37
	.byte	$31
	.byte	$30
	.byte	$2C
	.byte	$30
M0012:
	.byte	$12
	.byte	$C1
	.byte	$28
	.byte	$35
	.byte	$29

.endproc

; ---------------------------------------------------------------
; void __near__ call_parse_line (const char *s, const struct Line *expect_line, int line)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_call_parse_line: near

	.dbg	func, "call_parse_line", "00", static, "_call_parse_line"
	.dbg	sym, "s", "00", auto, 4
	.dbg	sym, "expect_line", "00", auto, 2
	.dbg	sym, "line", "00", auto, 0

.segment	"CODE"

	.dbg	line, "tests/parser_test.c", 210
	jsr     pushax
	.dbg	line, "tests/parser_test.c", 211
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00A5)
	ldx     #>(S00A5)
	jsr     pushax
	lda     #<(S00A6)
	ldx     #>(S00A6)
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0D
	jsr     ldaxysp
	jsr     pushax
	ldy     #$0A
	jsr     _fprintf
	.dbg	line, "tests/parser_test.c", 212
	lda     #<(_buffer)
	ldx     #>(_buffer)
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     _strcpy
	.dbg	line, "tests/parser_test.c", 213
	jsr     _parse_line
	.dbg	line, "tests/parser_test.c", 214
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00A7)
	ldx     #>(S00A7)
	jsr     pushax
	lda     #<(S00A8)
	ldx     #>(S00A8)
	jsr     pushax
	ldx     #$00
	lda     #$D6
	jsr     pushax
	lda     #<(S00A9)
	ldx     #>(S00A9)
	jsr     pushax
	ldx     #$00
	lda     _buffer_pos
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _buffer_pos
	jsr     axulong
	jsr     pusheax
	lda     #<(S00AA)
	ldx     #>(S00AA)
	jsr     pushax
	lda     #<(S00AB)
	ldx     #>(S00AB)
	jsr     pushax
	ldy     #$1B
	jsr     ldaxysp
	jsr     _strlen
	jsr     axulong
	jsr     pusheax
	ldy     #$1F
	jsr     ldaxysp
	jsr     _strlen
	jsr     axulong
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _buffer_pos
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     _strlen
	jsr     toseqax
	jeq     L0005
	jmp     L0006
L0005:	lda     #<(S00AC)
	ldx     #>(S00AC)
	jsr     pushax
	ldx     #$00
	lda     #$D6
	jsr     ___afailed
L0006:	lda     #<(S00AD)
	ldx     #>(S00AD)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/parser_test.c", 215
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00AE)
	ldx     #>(S00AE)
	jsr     pushax
	lda     #<(S00AF)
	ldx     #>(S00AF)
	jsr     pushax
	ldx     #$00
	lda     #$D7
	jsr     pushax
	ldy     #$0B
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     pushax
	ldy     #$0A
	jsr     _fprintf
	lda     #<(S00B0)
	ldx     #>(S00B0)
	jsr     pushax
	lda     #<(_line_buffer)
	ldx     #>(_line_buffer)
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     _hexdump
	lda     #<(S00B1)
	ldx     #>(S00B1)
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     _hexdump
	lda     #<(_line_buffer)
	ldx     #>(_line_buffer)
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     _memcmp
	cpx     #$00
	bne     L000A
	cmp     #$00
L000A:	jsr     booleq
	jeq     L000B
	jmp     L000C
L000B:	lda     #<(S00B2)
	ldx     #>(S00B2)
	jsr     pushax
	ldx     #$00
	lda     #$D7
	jsr     ___afailed
L000C:	lda     #<(S00B3)
	ldx     #>(S00B3)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/parser_test.c", 216
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00B4)
	ldx     #>(S00B4)
	jsr     pushax
	lda     #<(S00B5)
	ldx     #>(S00B5)
	jsr     pushax
	ldx     #$00
	lda     #$D8
	jsr     pushax
	lda     #<(S00B6)
	ldx     #>(S00B6)
	jsr     pushax
	ldx     #$00
	lda     _line_pos
	jsr     axulong
	jsr     pusheax
	ldx     #$00
	lda     _line_pos
	jsr     axulong
	jsr     pusheax
	lda     #<(S00B7)
	ldx     #>(S00B7)
	jsr     pushax
	lda     #<(S00B8)
	ldx     #>(S00B8)
	jsr     pushax
	ldy     #$19
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     axulong
	jsr     pusheax
	ldy     #$1D
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     axulong
	jsr     pusheax
	ldy     #$1E
	jsr     _fprintf
	ldx     #$00
	lda     _line_pos
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	jsr     ldauidx
	jsr     toseqax
	jeq     L0010
	jmp     L0011
L0010:	lda     #<(S00B9)
	ldx     #>(S00B9)
	jsr     pushax
	ldx     #$00
	lda     #$D8
	jsr     ___afailed
L0011:	lda     #<(S00BA)
	ldx     #>(S00BA)
	jsr     pushax
	lda     _stderr
	ldx     _stderr+1
	jsr     _fputs
	.dbg	line, "tests/parser_test.c", 217
	jsr     incsp6
	rts

	.dbg	line
.endproc

; ---------------------------------------------------------------
; void __near__ test_parse_line (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_test_parse_line: near

	.dbg	func, "test_parse_line", "00", static, "_test_parse_line"
	.dbg	sym, "line_1", "00", auto, -9
	.dbg	sym, "line_2", "00", auto, -21
	.dbg	sym, "line_3", "00", auto, -26

.segment	"CODE"

	.dbg	line, "tests/parser_test.c", 221
	ldy     #$09
	jsr     subysp
	ldy     #$08
L0002:	lda     M0001,y
	sta     (c_sp),y
	dey
	bpl     L0002
	.dbg	line, "tests/parser_test.c", 222
	ldy     #$0C
	jsr     subysp
	ldy     #$0B
L0003:	lda     M0002,y
	sta     (c_sp),y
	dey
	bpl     L0003
	.dbg	line, "tests/parser_test.c", 223
	jsr     decsp5
	ldy     #$04
L0004:	lda     M0003,y
	sta     (c_sp),y
	dey
	bpl     L0004
	.dbg	line, "tests/parser_test.c", 225
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S00BB)
	ldx     #>(S00BB)
	jsr     pushax
	lda     #<(S00BC)
	ldx     #>(S00BC)
	jsr     pushax
	ldy     #$06
	jsr     _fprintf
	.dbg	line, "tests/parser_test.c", 227
	lda     #<(S00BD)
	ldx     #>(S00BD)
	jsr     pushax
	lda     #$13
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$E3
	jsr     _call_parse_line
	.dbg	line, "tests/parser_test.c", 228
	lda     #<(S00BE)
	ldx     #>(S00BE)
	jsr     pushax
	lda     #$07
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$E4
	jsr     _call_parse_line
	.dbg	line, "tests/parser_test.c", 229
	lda     #<(S00BF)
	ldx     #>(S00BF)
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	jsr     pushax
	ldx     #$00
	lda     #$E5
	jsr     _call_parse_line
	.dbg	line, "tests/parser_test.c", 230
	ldy     #$1A
	jsr     addysp
	rts

	.dbg	line
.segment	"RODATA"

M0001:
	.byte	$09
	.word	$FFFF
	.byte	$03
	.byte	$D8
	.byte	$3D
	.byte	$31
	.byte	$30
	.byte	$30
M0002:
	.byte	$0C
	.word	$FFFF
	.byte	$03
	.byte	$D8
	.byte	$3D
	.byte	$31
	.byte	$30
	.byte	$30
	.byte	$08
	.byte	$02
	.byte	$D8
M0003:
	.byte	$05
	.word	$000A
	.byte	$02
	.byte	$31

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

	.dbg	func, "main", "00", static, "_main"

.segment	"CODE"

	.dbg	line, "tests/parser_test.c", 233
	jsr     _initialize_target
	.dbg	line, "tests/parser_test.c", 234
	jsr     _test_pvm_number
	.dbg	line, "tests/parser_test.c", 235
	jsr     _test_pvm_string
	.dbg	line, "tests/parser_test.c", 236
	jsr     _test_pvm_name
	.dbg	line, "tests/parser_test.c", 237
	jsr     _test_pvm_expression
	.dbg	line, "tests/parser_test.c", 238
	jsr     _test_pvm_statement
	.dbg	line, "tests/parser_test.c", 239
	jsr     _test_parse_line
	.dbg	line, "tests/parser_test.c", 240
	ldx     #$00
	lda     #$00
	jmp     L0001
	.dbg	line, "tests/parser_test.c", 241
L0001:	rts

	.dbg	line
.endproc

