; cc65 runtime
.include "zeropage.inc"

; sim65 vectors
.import exit

; Generated by linker
.import __MAIN_START__, __MAIN_SIZE__
.import __STACKSIZE__

.include "../target.inc"

.segment "STARTUP"

startup:
        cld                             ; Clear decimal flag
        ldx     #$FF
        txs                             ; Initialize the stack to $FF
        lda     #<(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        ldx     #>(__MAIN_START__ + __MAIN_SIZE__ + __STACKSIZE__)
        sta     sp
        stx     sp+1                    ; Set up C stack
        jsr     main        
        jmp     exit                    ; Return 0 from sim65
