source [file join [file dirname [info script]] common.expinc]
spawn_basic

# Explicit DIM

test {
DIM A(100)
LET A(1)=10
LET A(100)=1000
PRINT A(1),A(2),A(100)
} {
10         0               1000
}

# Implicit DIM

test {
LET X(1)=10
PRINT X(1)
PRINT X(11)
} {
10

READY

ERROR: OUT OF RANGE
}

# String array

test {
LET A$(1)="HELLO"
LET A$(2)="WORLD"
PRINT A$(1);", ";A$(2)
} {
HELLO, WORLD
}

# Multiple dimensions

test {
DIM M(5,5)
FOR I=1 TO 5:FOR J=1 TO 5:LET M(I,J)=I*J:NEXT J:NEXT I
PRINT M(1,1),M(2,2),M(4,3),M(5,5)
} {
1               4               12              25
}
