# SPDX-FileCopyrightText: 2022-2026 Willis Blackburn
#
# SPDX-License-Identifier: MIT

source [file join [file dirname [info script]] common.expinc]
spawn_basic

# Numbers

test "PRINT 0\n" "0\n"
test "PRINT 0.0\n" "0\n"
test "PRINT 1\n" "1\n"
test "PRINT 1.0\n" "1\n"
test "PRINT 2\n" "2\n"
test "PRINT 10\n" "10\n"
test "PRINT 3.14159\n" "3.14159\n"
test "PRINT -1\n" "-1\n"
test "PRINT -1.0\n" "-1\n"
test "PRINT -3.14159\n" "-3.14159\n"

# Simple expressions

test "PRINT 1+1\n" "2\n"
test "PRINT 1-1\n" "0\n"
test "PRINT 1*1\n" "1\n"
test "PRINT 1/1\n" "1\n"
test "PRINT 1+3.14159\n" "4.141590001\n"
test "PRINT 1-3.14159\n" "-2.14159\n"
test "PRINT 2*3.14159\n" "6.28318\n"

# Relational and logical operators

test "PRINT 1=1\n" "1\n"
test "PRINT 1=0\n" "0\n"

test "PRINT 1<>1\n" "0\n"
test "PRINT 1<>0\n" "1\n"

test "PRINT 1<2\n" "1\n"
test "PRINT 1<1\n" "0\n"
test "PRINT 1<0\n" "0\n"

test "PRINT 1<=2\n" "1\n"
test "PRINT 1<=1\n" "1\n"
test "PRINT 1<=0\n" "0\n"

test "PRINT 2>1\n" "1\n"
test "PRINT 1>1\n" "0\n"
test "PRINT 1>0\n" "1\n"

test "PRINT 2>=1\n" "1\n"
test "PRINT 1>=1\n" "1\n"
test "PRINT 1>=0\n" "1\n"

test "PRINT 1 OR 2\n" "3\n"
test "PRINT 1 AND 2\n" "0\n"

test "PRINT 1=0 OR 0=0\n" "1\n"
test "PRINT 1=0 OR 2=1\n" "0\n"
test "PRINT 1=1 AND 0=0\n" "1\n"
test "PRINT 1=1 AND 2=1\n" "0\n"

# Precedence

test "PRINT 1+2*3\n" "7\n"
test "PRINT 1+(2*3)\n" "7\n"
test "PRINT (1+2)*3\n" "9\n"
test "PRINT (3*2+1)*3\n" "21\n"
test "PRINT (3*(2+1))*3\n" "27\n"
