# SPDX-FileCopyrightText: 2022-2026 Willis Blackburn
#
# SPDX-License-Identifier: MIT

source [file join [file dirname [info script]] common.expinc]
spawn_basic

# ASC

test {
PRINT ASC("A")
} {
65
}

# CHR$

test {
PRINT CHR$(65)
} {
A
}

# LEFT$, RIGHT$, MID$

test {
PRINT LEFT$("HELLO",2)
} {
HE
}

test {
PRINT LEFT$("HELLO",100)
} {
HELLO
}

test {
PRINT LEFT$("HELLO",0)
} {

}

test {
PRINT LEFT$("HELLO",-1)
} {
ERR: RANGE
}

test {
PRINT RIGHT$("HELLO",2)
} {
LO
}

test {
PRINT RIGHT$("HELLO",100)
} {
HELLO
}

test {
PRINT RIGHT$("HELLO",0)
} {

}

test {
PRINT RIGHT$("HELLO",-1)
} {
ERR: RANGE
}

test {
PRINT MID$("HELLO",2,3)
} {
ELL
}

test {
PRINT MID$("HELLO",1,100)
} {
ELLO
}

test {
PRINT MID$("HELLO",1,0)
} {

}

test {
PRINT MID$("HELLO",1,-1)
} {
ERR: RANGE
}

test {
PRINT MID$("HELLO",0,1)
} {
ERR: RANGE
}

test {
PRINT MID$("HELLO",-1,1)
} {
ERR: RANGE
}

test {
LET H$="HELLO"
PRINT LEFT$(H$,1)&MID$(H$,2,3)&RIGHT$(H$,1)
} {
HELLO
}

# LEN

test {
PRINT LEN("HELLO")
} {
5
}

# STR$

test {
PRINT STR$(25)
} {
25
}

test {
PRINT STR$(3.14159)
} {
3.14159
}

# VAL

test {
PRINT VAL("3.14159")
} {
3.14159
}

# INT, ABS, SGN

test {
PRINT INT(3.9),INT(-3.1),INT(-3.9)
} {
3               -4              -4
}

test {
PRINT INT()
} {
ERR: ARITY?
}

test {
PRINT INT(1, 2)
} {
ERR: ARITY?
}

test {
PRINT ABS(3.14), ABS(-3.14), ABS(0)
} {
3.14            3.14            0
}

test {
PRINT ABS()
} {
ERR: ARITY?
}

test {
PRINT ABS(1,2)
} {
ERR: ARITY?
}

test {
PRINT SGN(5),SGN(-5),SGN(0)
} {
1               -1              0
}

test {
PRINT SGN()
} {
ERR: ARITY?
}

test {
PRINT SGN(1,2)
} {
ERR: ARITY?
}

# FRE
test {
PRINT FRE()<0 OR FRE()>0
} {
1
}

# RND

test {
PRINT RND(1)>=0 AND RND(1)<1
} {
1
}

test {
LET R1=RND(1):LET R2=RND(1):PRINT R1<>R2
} {
1
}

test {
PRINT RND(0)=RND(0)
} {
1
}

# RND(-1) and RND(-2) produce the same seed because they have the same normalized mantissa.
test {
PRINT RND(-1)=RND(-2)
} {
1
}
