# SPDX-FileCopyrightText: 2022-2026 Willis Blackburn
#
# SPDX-License-Identifier: MIT

source [file join [file dirname [info script]] common.expinc]
spawn_basic

# INPUT

send_echo {
INPUT X
}
expect -ex "?"
send_echo {
4
}
test {
PRINT X
} {
4
}

# Multiple values on one line

send_echo {
INPUT X,Y
}
expect -ex "?"
send_echo {
5,6
}
test {
PRINT X
} {
5
}
test {
PRINT Y
} {
6
}

# Multiple values on multiple lines

send_echo {
INPUT X,Y
}
expect -ex "?"
send_echo {
5
}
expect -ex "?"
send_echo {
6
}
test {
PRINT X
} {
5
}
test {
PRINT Y
} {
6
}

# Strings

send_echo {
INPUT A$
}
expect -ex "?"
send_echo {
HELLO
}
test {
PRINT A$
} {
HELLO
}

# Mutiple strings

send_echo {
INPUT FIRST$,LAST$
}
expect -ex "?"
send_echo {
WILLIS,BLACKBURN
}
test {
PRINT FIRST$
} {
WILLIS
}
test {
PRINT LAST$
} {
BLACKBURN
}

# Mutiple strings

send_echo {
INPUT A$,B$,C$
}
expect -ex "?"
send_echo {
HELLO," WORLD"," WITH ""QUOTES"""
}
test {
PRINT A$;B$;C$
} {
HELLO WORLD WITH "QUOTES"
}
