# SPDX-FileCopyrightText: 2022-2026 Willis Blackburn
#
# SPDX-License-Identifier: MIT

source [file join [file dirname [info script]] common.expinc]
spawn_basic

# LET

test {
LET X=1
PRINT X
} {
1
}

test {
LET X=X+1
PRINT X
} {
2
}

# Strings

test {
LET MSG$="HELLO, WORLD"
PRINT MSG$
} {
HELLO, WORLD
}

test {
LET A$="HELLO"
LET B$=A$&", WORLD"
PRINT A$,B$
} {
HELLO           HELLO, WORLD
}

test {
LET A$="HELLO"
LET B$=A$&", WORLD"
PRINT A$,B$
} {
HELLO           HELLO, WORLD
}
