# SPDX-FileCopyrightText: 2022-2026 Willis Blackburn
#
# SPDX-License-Identifier: MIT

source [file join [file dirname [info script]] common.expinc]
spawn_basic

# PEEK and POKE

test {
10 LET A$="HELLO"
20 LET ADDR=ADR(A$)
30 PRINT PEEK(ADDR)
40 PRINT PEEK(ADDR+1)
50 PRINT PEEK(ADDR+2)
60 PRINT PEEK(ADDR+3)
70 PRINT PEEK(ADDR+4)
80 POKE ADDR,80
90 PRINT A$
RUN
} {
72
69
76
76
79
PELLO

READY
}

test {
PRINT PEEK()
} {
ERR: ARITY?
}

test {
PRINT PEEK(ADDR, 1)
} {
ERR: ARITY?
}

# DPEEK and DPOKE

test {
NEW
} {
READY
}

test {
10 LET A$="HELLO"
20 LET ADDR=ADR(A$)
30 PRINT DPEEK(ADDR)
40 DPOKE ADDR,18761
50 PRINT A$
RUN
} {
17736
IILLO

READY
}

test {
PRINT DPEEK()
} {
ERR: ARITY?
}

test {
PRINT DPEEK(ADDR, 1)
} {
ERR: ARITY?
}

test {
DPOKE ADDR
} {
ERR: SYNTAX
}

test {
DPOKE ADDR, 1, 2
} {
ERR: SYNTAX
}


