# SPDX-FileCopyrightText: 2022-2026 Willis Blackburn
#
# SPDX-License-Identifier: MIT

source [file join [file dirname [info script]] common.expinc]
spawn_basic

# SIN

test "PRINT SIN(0)\n" "0\n"
test "PRINT SIN(1)\n" "0.841470985\n"

# COS

test "PRINT COS(0)\n" "1\n"
test "PRINT COS(1)\n" "0.540301189\n"

# TAN

test "PRINT TAN(0)\n" "0\n"
test "PRINT TAN(1)\n" "1.55741094\n"

# ATN

test "PRINT ATN(0)\n" "0\n"
test "PRINT ATN(1)\n" "0.78539636\n"
test "PRINT ATN(0.5)\n" "0.463647589\n"
test "PRINT ATN(2)\n" "1.10714741\n"
test "PRINT ATN(-1)\n" "-0.78539636\n"

# LOG

test "PRINT LOG(1)\n" "0\n"
test "PRINT LOG(2.71828183)\n" "1\n"

# EXP

test "PRINT EXP(0)\n" "1\n"
test "PRINT EXP(1)\n" "2.71828183\n"

# SQR

test "PRINT SQR(4)\n" "2\n"
test "PRINT SQR(2)\n" "1.41421356\n"
