# SPDX-FileCopyrightText: 2022-2026 Willis Blackburn
#
# SPDX-License-Identifier: MIT

source [file join [file dirname [info script]] common.expinc]
spawn_basic

# USR

# The DATA values encode a program that shifts AX left by one bit, multiplying it by 2:
#     ASL A
#     TAY
#     TXA
#     ROL A
#     TAX
#     TYA
#     RTS

test {
10 DATA 10,168,138,42,170,152,96
20 FOR I=1 TO 7
30 READ B:LET SHIFT$=SHIFT$&CHR$(B)
40 NEXT I
50 PRINT USR(ADR(SHIFT$),1023)
RUN
} {
2046
}

